# Generated by Django 4.2.30 on 2026-07-23 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name_sw', models.CharField(max_length=150, unique=True, verbose_name='name in Kiswahili')),
                ('name_en', models.CharField(max_length=150, unique=True, verbose_name='name in English')),
                ('code', models.CharField(help_text='Use a short unique code, for example EXHIBITION or MEETING.', max_length=30, unique=True, verbose_name='category code')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='slug')),
                ('description_sw', models.TextField(blank=True, verbose_name='description in Kiswahili')),
                ('description_en', models.TextField(blank=True, verbose_name='description in English')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'event category',
                'verbose_name_plural': 'event categories',
                'ordering': ['display_order', 'name_sw'],
            },
        ),
    ]

