# Generated by Django 4.2.30 on 2026-07-23 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_council_council_unique_council_code_per_region_and_more'),
        ('events', '0002_venue_venue_unique_venue_name_per_district'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='venue',
            name='unique_venue_name_per_district',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='district',
        ),
        migrations.AddField(
            model_name='venue',
            name='council',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='venues', to='core.council', verbose_name='council'),
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(fields=('name', 'council'), name='unique_venue_name_per_council'),
        ),
    ]

