# Generated by Django 4.2.30 on 2026-07-23 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_remove_venue_unique_venue_name_per_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(help_text='Use a short unique code, for example ELIMU-2026.', max_length=50, unique=True, verbose_name='event code')),
                ('title_sw', models.CharField(max_length=250, verbose_name='event title in Kiswahili')),
                ('title_en', models.CharField(max_length=250, verbose_name='event title in English')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True, verbose_name='slug')),
                ('description_sw', models.TextField(blank=True, verbose_name='description in Kiswahili')),
                ('description_en', models.TextField(blank=True, verbose_name='description in English')),
                ('organizer_name', models.CharField(max_length=250, verbose_name='organizer name')),
                ('contact_person', models.CharField(blank=True, max_length=150, verbose_name='contact person')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='contact phone')),
                ('registration_opens_at', models.DateTimeField(blank=True, null=True, verbose_name='registration opens')),
                ('registration_closes_at', models.DateTimeField(blank=True, null=True, verbose_name='registration closes')),
                ('starts_at', models.DateTimeField(verbose_name='event starts')),
                ('ends_at', models.DateTimeField(verbose_name='event ends')),
                ('maximum_participants', models.PositiveIntegerField(blank=True, help_text='Leave empty when the event has no participant limit.', null=True, verbose_name='maximum participants')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='events/logos/', verbose_name='event logo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='events/banners/', verbose_name='event banner')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('REGISTRATION_OPEN', 'Registration Open'), ('REGISTRATION_CLOSED', 'Registration Closed'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30, verbose_name='status')),
                ('is_public', models.BooleanField(default=True, help_text='Public events may be viewed without signing in.', verbose_name='public event')),
                ('registration_enabled', models.BooleanField(default=True, verbose_name='registration enabled')),
                ('evaluation_enabled', models.BooleanField(default=False, verbose_name='evaluation enabled')),
                ('qr_checkin_enabled', models.BooleanField(default=True, verbose_name='QR check-in enabled')),
                ('badge_enabled', models.BooleanField(default=True, verbose_name='badge printing enabled')),
                ('certificate_enabled', models.BooleanField(default=False, verbose_name='certificate enabled')),
                ('booth_enabled', models.BooleanField(default=False, verbose_name='booth management enabled')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.eventcategory', verbose_name='event category')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.venue', verbose_name='venue')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['-starts_at', 'title_sw'],
                'indexes': [models.Index(fields=['status', 'starts_at'], name='event_status_start_idx'), models.Index(fields=['category', 'status'], name='event_category_status_idx')],
            },
        ),
    ]

