# Generated by Django 4.2.30 on 2026-07-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer_name_en',
            field=models.CharField(blank=True, max_length=250, verbose_name='organizer name in English'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_name_sw',
            field=models.CharField(blank=True, max_length=250, verbose_name='organizer name in Kiswahili'),
        ),
    ]

