# Generated by Django 4.2.30 on 2026-07-24 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_organizer_name_en_event_organizer_name_sw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer_name',
        ),
    ]

