# Generated by Django 4.2.30 on 2026-08-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_organizer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='participation fee'),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_currency',
            field=models.CharField(default='TZS', max_length=3, verbose_name='payment currency'),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_enabled',
            field=models.BooleanField(default=False, verbose_name='payment collection enabled'),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_instructions_en',
            field=models.TextField(blank=True, verbose_name='payment instructions in English'),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_instructions_sw',
            field=models.TextField(blank=True, verbose_name='payment instructions in Kiswahili'),
        ),
    ]

