# Generated by Django 4.2.30 on 2026-08-10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0007_event_participation_fee_event_payment_currency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialEventParticipant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("source_sheet", models.CharField(max_length=100, verbose_name="source sheet")),
                ("source_number", models.CharField(max_length=50, verbose_name="source row number")),
                ("source_row_index", models.PositiveIntegerField(default=0, editable=False, verbose_name="source row position")),
                ("full_name", models.CharField(max_length=300, verbose_name="participant name")),
                ("institution", models.TextField(blank=True, verbose_name="institution")),
                ("research_title", models.TextField(blank=True, verbose_name="research title")),
                ("research_field", models.TextField(blank=True, verbose_name="research field")),
                ("verification_token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="verification token")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created_records", to=settings.AUTH_USER_MODEL, verbose_name="created by")),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="special_event_participants", to="events.event", verbose_name="special event")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_updated_records", to=settings.AUTH_USER_MODEL, verbose_name="updated by")),
            ],
            options={
                "verbose_name": "special event participant",
                "verbose_name_plural": "special event participants",
                "ordering": ["event", "source_sheet", "source_row_index", "full_name"],
                "indexes": [models.Index(fields=["event", "source_sheet", "is_active"], name="special_event_participant_idx")],
                "constraints": [models.UniqueConstraint(fields=("event", "source_sheet", "source_number"), name="unique_special_event_source_row")],
            },
        ),
    ]

