# Generated by Django 4.2.29 on 2026-08-23 14:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0013_preserve_weuutz_code_casing'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title_sw', models.CharField(default='Ratiba ya tukio', max_length=250, verbose_name='timetable title in Kiswahili')),
                ('title_en', models.CharField(default='Event timetable', max_length=250, verbose_name='timetable title in English')),
                ('pdf_file', models.FileField(upload_to='events/timetables/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='PDF timetable')),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public token')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='events.event', verbose_name='event')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'event timetable',
                'verbose_name_plural': 'event timetables',
            },
        ),
    ]
