# Generated by Django 4.2.30 on 2026-08-15 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_allow_blank_legacy_award_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceProgrammeContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('role', models.CharField(choices=[('SPEAKER', 'Speaker'), ('KEYNOTE_SPEAKER', 'Keynote speaker'), ('MODERATOR', 'Moderator'), ('PANELIST', 'Panelist'), ('FACILITATOR', 'Facilitator')], default='SPEAKER', max_length=30, verbose_name='programme role')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ConferenceSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('full_name', models.CharField(max_length=200, verbose_name='full name')),
                ('position_title', models.CharField(blank=True, max_length=200, verbose_name='position / title')),
                ('institution', models.CharField(blank=True, max_length=250, verbose_name='institution')),
                ('biography', models.TextField(blank=True, verbose_name='short biography')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='conferences/speakers/', verbose_name='photo')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_speakers', to='events.event', verbose_name='conference event')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'ordering': ('display_order', 'full_name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ConferenceProgrammeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=80, verbose_name='programme item code')),
                ('item_type', models.CharField(choices=[('OPENING', 'Opening'), ('KEYNOTE', 'Keynote address'), ('PRESENTATION', 'Presentation'), ('PANEL', 'Panel discussion'), ('WORKSHOP', 'Workshop'), ('BREAK', 'Break'), ('NETWORKING', 'Networking'), ('CLOSING', 'Closing'), ('OTHER', 'Other')], default='PRESENTATION', max_length=20, verbose_name='programme item type')),
                ('title', models.CharField(max_length=300, verbose_name='programme title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('starts_at', models.DateTimeField(verbose_name='programme item starts')),
                ('ends_at', models.DateTimeField(verbose_name='programme item ends')),
                ('venue_name', models.CharField(blank=True, max_length=250, verbose_name='venue')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_items', to='conferences.conferencesession', verbose_name='conference session')),
                ('speakers', models.ManyToManyField(blank=True, related_name='programme_items', through='conferences.ConferenceProgrammeContributor', to='conferences.conferencespeaker', verbose_name='speakers and facilitators')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'ordering': ('starts_at', 'display_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='conferenceprogrammecontributor',
            name='programme_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='conferences.conferenceprogrammeitem', verbose_name='programme item'),
        ),
        migrations.AddField(
            model_name='conferenceprogrammecontributor',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_contributions', to='conferences.conferencespeaker', verbose_name='speaker / facilitator'),
        ),
        migrations.AddField(
            model_name='conferenceprogrammecontributor',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddConstraint(
            model_name='conferencespeaker',
            constraint=models.UniqueConstraint(fields=('event', 'full_name', 'institution'), name='unique_conference_speaker_per_event'),
        ),
        migrations.AddConstraint(
            model_name='conferenceprogrammeitem',
            constraint=models.UniqueConstraint(fields=('session', 'code'), name='unique_programme_item_code_per_session'),
        ),
        migrations.AddConstraint(
            model_name='conferenceprogrammecontributor',
            constraint=models.UniqueConstraint(fields=('programme_item', 'speaker', 'role'), name='unique_contributor_role_per_programme_item'),
        ),
    ]

