# Generated by Django 4.2.30 on 2026-08-16 07:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0010_allow_blank_legacy_award_year'),
        ('conferences', '0002_conferenceprogrammecontributor_conferencespeaker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceCallForPapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=250, verbose_name='call title')),
                ('introduction', models.TextField(verbose_name='introduction')),
                ('guidelines', models.TextField(verbose_name='submission guidelines')),
                ('opens_at', models.DateTimeField(blank=True, null=True, verbose_name='opens at')),
                ('closes_at', models.DateTimeField(blank=True, null=True, verbose_name='closes at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conference_call_for_papers', to='events.event', verbose_name='conference event')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'conference call for papers',
                'verbose_name_plural': 'conference calls for papers',
            },
        ),
        migrations.CreateModel(
            name='ConferencePaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reference_number', models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='reference number')),
                ('submission_type', models.CharField(choices=[('ABSTRACT', 'Abstract'), ('FULL_PAPER', 'Full paper')], default='ABSTRACT', max_length=20, verbose_name='submission type')),
                ('presentation_format', models.CharField(choices=[('ORAL', 'Oral presentation'), ('POSTER', 'Poster presentation'), ('PANEL', 'Panel contribution'), ('WORKSHOP', 'Workshop contribution')], default='ORAL', max_length=20, verbose_name='preferred presentation format')),
                ('title', models.CharField(max_length=400, verbose_name='research / paper title')),
                ('abstract', models.TextField(verbose_name='abstract')),
                ('thematic_area', models.CharField(max_length=250, verbose_name='thematic area')),
                ('keywords', models.CharField(blank=True, max_length=400, verbose_name='keywords')),
                ('corresponding_author', models.CharField(max_length=200, verbose_name='corresponding author')),
                ('institution', models.CharField(max_length=250, verbose_name='institution')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('phone', models.CharField(max_length=40, verbose_name='phone number')),
                ('co_authors', models.TextField(blank=True, help_text='Enter one co-author per line, including institution where applicable.', verbose_name='co-authors')),
                ('document', models.FileField(blank=True, null=True, upload_to='conferences/papers/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(('pdf', 'doc', 'docx'))], verbose_name='abstract or paper document')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('REVISION_REQUIRED', 'Revision required'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='SUBMITTED', max_length=30, verbose_name='review status')),
                ('decision_message', models.TextField(blank=True, verbose_name='message to the author')),
                ('internal_notes', models.TextField(blank=True, verbose_name='internal review notes')),
                ('reviewed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='reviewed at')),
                ('assigned_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_papers', to='conferences.conferencesession', verbose_name='assigned conference session')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='conferences.conferencecallforpapers', verbose_name='call for papers')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('reviewed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_conference_papers', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ConferencePaperReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('decision', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('REVISION_REQUIRED', 'Revision required'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], max_length=30, verbose_name='decision')),
                ('message_to_author', models.TextField(blank=True, verbose_name='message to the author')),
                ('internal_notes', models.TextField(blank=True, verbose_name='internal notes')),
                ('assigned_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_review_assignments', to='conferences.conferencesession', verbose_name='assigned conference session')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_history', to='conferences.conferencepaper', verbose_name='conference paper')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conference_paper_reviews', to=settings.AUTH_USER_MODEL, verbose_name='reviewer')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='conferencepaper',
            constraint=models.UniqueConstraint(fields=('call', 'email', 'title'), name='unique_conference_paper_title_per_author'),
        ),
    ]

