# Generated by Django 4.2.30 on 2026-08-16 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0010_allow_blank_legacy_award_year'),
        ('conferences', '0003_conferencecallforpapers_conferencepaper_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('institution', models.CharField(blank=True, max_length=250, verbose_name='institution')),
                ('expertise', models.TextField(help_text='Enter the research fields or thematic areas this reviewer can assess.', verbose_name='areas of expertise')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_reviewers', to='events.event', verbose_name='conference event')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_reviewer_profiles', to=settings.AUTH_USER_MODEL, verbose_name='reviewer account')),
            ],
            options={
                'ordering': ('user__first_name', 'user__last_name', 'user__username'),
            },
        ),
        migrations.CreateModel(
            name='ConferencePaperReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='review deadline')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CONFLICT', 'Conflict of interest')], default='ASSIGNED', max_length=20, verbose_name='assignment status')),
                ('conflict_reason', models.TextField(blank=True, verbose_name='conflict reason')),
                ('relevance_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='relevance score')),
                ('originality_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='originality score')),
                ('methodology_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='methodology score')),
                ('clarity_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='clarity score')),
                ('impact_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='potential impact score')),
                ('recommendation', models.CharField(blank=True, choices=[('ACCEPT', 'Accept'), ('MINOR_REVISION', 'Minor revision'), ('MAJOR_REVISION', 'Major revision'), ('REJECT', 'Reject')], max_length=30, verbose_name='recommendation')),
                ('comments_to_author', models.TextField(blank=True, verbose_name='comments to the author')),
                ('confidential_comments', models.TextField(blank=True, verbose_name='confidential comments')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='review submitted at')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_conference_paper_reviews', to=settings.AUTH_USER_MODEL, verbose_name='assigned by')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_review_assignments', to='conferences.conferencepaper', verbose_name='conference paper')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='conferences.conferencereviewer', verbose_name='reviewer')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'ordering': ('due_at', 'created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='conferencereviewer',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_reviewer_per_conference'),
        ),
        migrations.AddConstraint(
            model_name='conferencepaperreviewassignment',
            constraint=models.UniqueConstraint(fields=('paper', 'reviewer'), name='unique_reviewer_assignment_per_paper'),
        ),
    ]

