# Generated by Django 4.2.30 on 2026-08-16 08:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conferences', '0004_conferencereviewer_conferencepaperreviewassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferencePresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('presenter_name', models.CharField(max_length=200, verbose_name='presenter name')),
                ('starts_at', models.DateTimeField(verbose_name='presentation starts')),
                ('ends_at', models.DateTimeField(verbose_name='presentation ends')),
                ('venue_name', models.CharField(blank=True, max_length=250, verbose_name='presentation venue')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed by presenter'), ('READY', 'Slides received / ready'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20, verbose_name='presentation status')),
                ('slides', models.FileField(blank=True, null=True, upload_to='conferences/presentations/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(('pdf', 'ppt', 'pptx'))], verbose_name='presentation slides')),
                ('presenter_notes', models.TextField(blank=True, verbose_name='presenter notes')),
                ('manager_notes', models.TextField(blank=True, verbose_name='manager notes')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmed at')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presentation', to='conferences.conferencepaper', verbose_name='accepted paper')),
                ('programme_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_presentations', to='conferences.conferenceprogrammeitem', verbose_name='programme item')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paper_presentations', to='conferences.conferencesession', verbose_name='conference session')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'ordering': ('starts_at', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='conferencepresentation',
            constraint=models.UniqueConstraint(fields=('session', 'starts_at', 'venue_name'), name='unique_presentation_slot_per_venue'),
        ),
    ]

