# Generated by Django 4.2.30 on 2026-08-16 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conferences', '0005_conferencepresentation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferencePaperCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('communication_type', models.CharField(choices=[('ACKNOWLEDGEMENT', 'Submission acknowledgement'), ('REVISION', 'Revision request'), ('ACCEPTANCE', 'Acceptance notification'), ('REJECTION', 'Rejection notification'), ('PRESENTATION_INVITATION', 'Presentation invitation'), ('PRESENTATION_REMINDER', 'Presentation reminder'), ('OTHER', 'Other communication')], max_length=30, verbose_name='communication type')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='recipient email')),
                ('subject', models.CharField(max_length=300, verbose_name='email subject')),
                ('message', models.TextField(verbose_name='message')),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='delivery status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('failure_message', models.TextField(blank=True, verbose_name='failure message')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='conferences.conferencepaper', verbose_name='conference paper')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_conference_paper_communications', to=settings.AUTH_USER_MODEL, verbose_name='sent by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]

