# Generated by Django 4.2.30 on 2026-08-16 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_allow_blank_legacy_award_year'),
        ('forms_builder', '0024_alter_notificationlog_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conferences', '0006_conferencepapercommunication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('recipient_type', models.CharField(choices=[('PARTICIPANT', 'Participant'), ('PRESENTER', 'Presenter'), ('REVIEWER', 'Peer reviewer')], max_length=20, verbose_name='recipient type')),
                ('recipient_name', models.CharField(max_length=200, verbose_name='recipient name')),
                ('institution', models.CharField(blank=True, max_length=250, verbose_name='institution')),
                ('certificate_number', models.CharField(max_length=100, unique=True, verbose_name='certificate number')),
                ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='issued at')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='revoked')),
                ('revocation_reason', models.TextField(blank=True, verbose_name='revocation reason')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_certificates', to='events.event', verbose_name='conference event')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_conference_certificates', to=settings.AUTH_USER_MODEL, verbose_name='issued by')),
                ('paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conference_certificates', to='conferences.conferencepaper', verbose_name='presented paper')),
                ('participant_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conference_certificates', to='forms_builder.formsubmission', verbose_name='participant registration')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conference_certificates', to='conferences.conferencereviewer', verbose_name='peer reviewer')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'ordering': ('-issued_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='conferencecertificate',
            constraint=models.UniqueConstraint(condition=models.Q(('participant_submission__isnull', False)), fields=('event', 'recipient_type', 'participant_submission'), name='unique_participant_conference_certificate'),
        ),
        migrations.AddConstraint(
            model_name='conferencecertificate',
            constraint=models.UniqueConstraint(condition=models.Q(('paper__isnull', False)), fields=('event', 'recipient_type', 'paper'), name='unique_presenter_conference_certificate'),
        ),
        migrations.AddConstraint(
            model_name='conferencecertificate',
            constraint=models.UniqueConstraint(condition=models.Q(('reviewer__isnull', False)), fields=('event', 'recipient_type', 'reviewer'), name='unique_reviewer_conference_certificate'),
        ),
    ]

