# Generated by Django 4.2.30 on 2026-08-16 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0010_allow_blank_legacy_award_year'),
        ('conferences', '0007_conferencecertificate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='feedback reference')),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_anonymous', models.BooleanField(default=True, verbose_name='submit anonymously')),
                ('respondent_name', models.CharField(blank=True, max_length=200, verbose_name='respondent name')),
                ('institution', models.CharField(blank=True, max_length=250, verbose_name='institution')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('overall_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='overall experience')),
                ('content_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='content relevance and quality')),
                ('speakers_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='speakers and presentations')),
                ('organization_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='organization and communication')),
                ('venue_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='venue and facilities')),
                ('would_recommend', models.BooleanField(verbose_name='would recommend this conference')),
                ('most_valuable', models.TextField(blank=True, verbose_name='most valuable aspect')),
                ('improvements', models.TextField(blank=True, verbose_name='suggested improvements')),
                ('additional_comments', models.TextField(blank=True, verbose_name='additional comments')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_feedback', to='events.event', verbose_name='conference event')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback_responses', to='conferences.conferencesession', verbose_name='conference session')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]

