# Generated by Django 4.2.30 on 2026-08-17 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms_builder', '0024_alter_notificationlog_notification_type'),
        ('conferences', '0008_conferencefeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceGuidingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('text', models.TextField(verbose_name='question')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'ordering': ('topic', 'display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ConferenceGuidingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=500, verbose_name='guiding subtopic')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guiding_topics', to='conferences.conferencesession', verbose_name='conference session')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'ordering': ('session', 'display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ConferenceGuidingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('response', models.TextField(blank=True, verbose_name='response')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='conferences.conferenceguidingquestion', verbose_name='guiding question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_guiding_responses', to='forms_builder.formsubmission', verbose_name='participant registration')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'ordering': ('submission', 'question'),
            },
        ),
        migrations.AddField(
            model_name='conferenceguidingquestion',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='conferences.conferenceguidingtopic', verbose_name='guiding subtopic'),
        ),
        migrations.AddField(
            model_name='conferenceguidingquestion',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddConstraint(
            model_name='conferenceguidingtopic',
            constraint=models.UniqueConstraint(fields=('session', 'title'), name='unique_guiding_topic_per_session'),
        ),
        migrations.AddConstraint(
            model_name='conferenceguidingresponse',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='unique_participant_guiding_response'),
        ),
        migrations.AddConstraint(
            model_name='conferenceguidingquestion',
            constraint=models.UniqueConstraint(fields=('topic', 'text'), name='unique_guiding_question_per_topic'),
        ),
    ]

