# Generated by Django 4.2.30 on 2026-08-17 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms_builder', '0024_alter_notificationlog_notification_type'),
        ('conferences', '0009_conferenceguidingquestion_conferenceguidingtopic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceGuidingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=20, verbose_name='status')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guiding_submissions', to='conferences.conferencesession', verbose_name='conference session')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_guiding_submissions', to='forms_builder.formsubmission', verbose_name='participant registration')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'ordering': ('submission', 'session'),
            },
        ),
        migrations.AddConstraint(
            model_name='conferenceguidingsubmission',
            constraint=models.UniqueConstraint(fields=('submission', 'session'), name='unique_participant_guiding_session_submission'),
        ),
    ]

