# Generated by Django 4.2.30 on 2026-08-04 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_council_council_unique_council_code_per_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name_sw', models.CharField(max_length=160, verbose_name='name in Kiswahili')),
                ('name_en', models.CharField(max_length=160, verbose_name='name in English')),
                ('code', models.CharField(max_length=50, verbose_name='ward code')),
                ('slug', models.SlugField(blank=True, max_length=220, verbose_name='slug')),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='core.council', verbose_name='council')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'ward',
                'verbose_name_plural': 'wards',
                'ordering': ['council__region__name_sw', 'council__name_sw', 'name_sw'],
            },
        ),
        migrations.AddConstraint(
            model_name='ward',
            constraint=models.UniqueConstraint(fields=('council', 'code'), name='unique_ward_code_per_council'),
        ),
    ]

