# Generated by Django 4.2.30 on 2026-08-05 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ward_ward_unique_ward_code_per_council'),
    ]

    operations = [
        migrations.AddField(
            model_name='council',
            name='district',
            field=models.ForeignKey(blank=True, help_text='Optional district grouping within the selected region.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='councils', to='core.district', verbose_name='district'),
        ),
    ]

