from django.urls import path

from . import views


app_name = "conferences"

urlpatterns = [
    path(
        "participants/<uuid:participant_token>/discussion-questions/",
        views.participant_guiding_questions,
        name="participant_guiding_questions",
    ),
    path(
        "participants/<uuid:participant_token>/discussion-questions/<int:session_id>/",
        views.participant_session_guiding_questions,
        name="participant_session_guiding_questions",
    ),
    path(
        "conferences/<slug:event_slug>/programme/",
        views.public_programme,
        name="public_programme",
    ),
    path(
        "conferences/<slug:event_slug>/programme/download/",
        views.programme_download,
        name="programme_download",
    ),
    path(
        "conferences/<slug:event_slug>/papers/submit/",
        views.paper_submit,
        name="paper_submit",
    ),
    path(
        "conferences/<slug:event_slug>/feedback/",
        views.feedback_submit,
        name="feedback_submit",
    ),
    path(
        "conferences/<slug:event_slug>/feedback/qr.png",
        views.feedback_qr,
        name="feedback_qr",
    ),
    path(
        "conference-feedback/<uuid:public_token>/thank-you/",
        views.feedback_thanks,
        name="feedback_thanks",
    ),
    path(
        "conference-papers/<uuid:public_token>/",
        views.paper_status,
        name="paper_status",
    ),
    path(
        "conference-papers/<uuid:public_token>/document/",
        views.paper_document,
        name="paper_document",
    ),
    path(
        "conference-papers/<uuid:public_token>/presentation/confirm/",
        views.presentation_confirm,
        name="presentation_confirm",
    ),
    path(
        "conference-papers/<uuid:public_token>/presentation/slides/",
        views.presentation_slides,
        name="presentation_slides",
    ),
    path(
        "conference-papers/<uuid:public_token>/letter/",
        views.paper_letter,
        name="paper_letter",
    ),
    path(
        "conference-certificates/<uuid:verification_token>/",
        views.certificate_print,
        name="certificate_print",
    ),
    path(
        "conference-certificates/<uuid:verification_token>/verify/",
        views.certificate_verify,
        name="certificate_verify",
    ),
    path(
        "conference-certificates/<uuid:verification_token>/qr.png",
        views.certificate_qr,
        name="certificate_qr",
    ),
    path("staff/conferences/", views.conference_list, name="conference_list"),
    path(
        "staff/conferences/forms/<int:form_id>/",
        views.conference_detail,
        name="conference_detail",
    ),
    path(
        "staff/conferences/forms/<int:form_id>/participants/print/",
        views.participant_list_print,
        name="participant_list_print",
    ),
    path(
        "staff/conferences/forms/<int:form_id>/participants/excel/",
        views.participant_list_excel,
        name="participant_list_excel",
    ),
    path(
        "staff/conferences/forms/<int:form_id>/registrations/<int:submission_id>/<str:decision>/",
        views.registration_decision,
        name="registration_decision",
    ),
    path(
        "staff/conferences/forms/<int:form_id>/sessions/<int:session_id>/register/",
        views.session_register,
        name="session_register",
    ),
    path(
        "staff/conferences/forms/<int:form_id>/sessions/<int:session_id>/register/export/",
        views.session_register_csv,
        name="session_register_csv",
    ),
    path(
        "staff/conferences/forms/<int:form_id>/qr/",
        views.registration_qr,
        name="registration_qr",
    ),
    path(
        "staff/conferences/forms/<int:form_id>/papers/",
        views.paper_review_list,
        name="paper_review_list",
    ),
    path(
        "staff/conferences/forms/<int:form_id>/papers/<int:paper_id>/review/",
        views.paper_review,
        name="paper_review",
    ),
    path(
        "staff/conferences/forms/<int:form_id>/papers/<int:paper_id>/assign-reviewer/",
        views.assign_paper_reviewer,
        name="assign_paper_reviewer",
    ),
    path(
        "staff/conferences/peer-reviews/",
        views.reviewer_workspace,
        name="reviewer_workspace",
    ),
    path(
        "staff/conferences/peer-reviews/<int:assignment_id>/",
        views.peer_review,
        name="peer_review",
    ),
    path(
        "staff/conferences/forms/<int:form_id>/presentations/",
        views.presentation_list,
        name="presentation_list",
    ),
    path(
        "staff/conferences/forms/<int:form_id>/certificates/",
        views.certificate_list,
        name="certificate_list",
    ),
    path(
        "staff/conferences/forms/<int:form_id>/feedback/",
        views.feedback_dashboard,
        name="feedback_dashboard",
    ),
    path(
        "staff/conferences/forms/<int:form_id>/feedback/export/",
        views.feedback_csv,
        name="feedback_csv",
    ),
    path(
        "staff/conferences/forms/<int:form_id>/certificates/<int:certificate_id>/revoke/",
        views.certificate_revoke,
        name="certificate_revoke",
    ),
    path(
        "staff/conferences/forms/<int:form_id>/papers/<int:paper_id>/presentation/",
        views.presentation_schedule,
        name="presentation_schedule",
    ),
    path(
        "staff/conferences/forms/<int:form_id>/papers/<int:paper_id>/communications/",
        views.paper_communication,
        name="paper_communication",
    ),
]

