# Generated by Django 4.2.29 on 2026-03-25 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_taskassignment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permits', '0005_externalworkrequest_group_leader_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_no', models.CharField(max_length=50, unique=True)),
                ('request_type', models.CharField(choices=[('ADVANCE', 'Advance'), ('REIMBURSEMENT', 'Reimbursement'), ('DIRECT_PAYMENT', 'Direct Payment'), ('IMPRESS', 'Imprest'), ('SPECIAL_ACTIVITY', 'Special Activity')], max_length=30)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='TZS', max_length=10)),
                ('funding_source', models.CharField(blank=True, max_length=255)),
                ('financial_year', models.CharField(max_length=20)),
                ('vote_code', models.CharField(blank=True, max_length=50)),
                ('sub_vote', models.CharField(blank=True, max_length=50)),
                ('cost_centre', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('PARTIALLY_APPROVED', 'Partially Approved'), ('DISBURSED', 'Disbursed'), ('RETIRED', 'Retired'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Retirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retirement_no', models.CharField(max_length=50, unique=True)),
                ('amount_accounted', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_unaccounted', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('finance_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retirement', to='finance.financerequest')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retirements_submitted', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retirements_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='minutesheet',
            name='meeting_date',
        ),
        migrations.AddField(
            model_name='minutesheet',
            name='activity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minutesheet',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='finance/minute_sheets/'),
        ),
        migrations.AddField(
            model_name='minutesheet',
            name='estimated_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='minutesheet',
            name='justification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minutesheet',
            name='reference_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='minutesheet',
            name='related_permit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minute_sheets', to='permits.externalworkrequest'),
        ),
        migrations.AddField(
            model_name='minutesheet',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minute_sheets', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='minutesheet',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minute_sheets_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='minutesheet',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='minutesheet',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='minutesheet',
            name='unit_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='minutesheet',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='minutesheet',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='RetirementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('receipt_no', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='finance/retirements/')),
                ('retirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.retirement')),
            ],
        ),
        migrations.AddField(
            model_name='financerequest',
            name='minute_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_requests', to='finance.minutesheet'),
        ),
        migrations.AddField(
            model_name='financerequest',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_requests_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FinanceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('MINUTE_SHEET', 'Minute Sheet'), ('QUOTATION', 'Quotation'), ('INVOICE', 'Invoice'), ('RECEIPT', 'Receipt'), ('PAYMENT_VOUCHER', 'Payment Voucher'), ('APPROVAL_MEMO', 'Approval Memo'), ('RETIREMENT_REPORT', 'Retirement Report'), ('OTHER', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='finance/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('finance_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='finance.financerequest')),
                ('minute_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='finance.minutesheet')),
                ('retirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='finance.retirement')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disbursement_no', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(choices=[('BANK', 'Bank'), ('CASH', 'Cash'), ('MOBILE', 'Mobile'), ('CHEQUE', 'Cheque')], max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_account', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('disbursed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursements_made', to=settings.AUTH_USER_MODEL)),
                ('finance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='finance.financerequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('budget_code', models.CharField(blank=True, max_length=50)),
                ('expense_category', models.CharField(choices=[('TRANSPORT', 'Transport'), ('ACCOMMODATION', 'Accommodation'), ('FUEL', 'Fuel'), ('MEALS', 'Meals'), ('PRINTING', 'Printing'), ('ALLOWANCE', 'Allowance'), ('PROCUREMENT', 'Procurement'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('finance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='finance.financerequest')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(choices=[('HEAD_OF_UNIT', 'Head of Unit'), ('DIRECTOR', 'Director'), ('FINANCE_OFFICER', 'Finance Officer'), ('ACCOUNTANT', 'Accountant'), ('FINAL_APPROVER', 'Final Approver')], max_length=30)),
                ('action', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned'), ('COMMENTED', 'Commented')], default='PENDING', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('sequence_no', models.PositiveIntegerField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('finance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='finance.financerequest')),
            ],
            options={
                'ordering': ['sequence_no'],
            },
        ),
    ]
