# Generated by Django 4.2.29 on 2026-04-26 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financerequest_retirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetline',
            name='amount_disbursed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='budgeted_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='financial_year',
            field=models.CharField(default='2025/2026', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetline',
            name='month',
            field=models.CharField(choices=[('JULY', 'July'), ('AUGUST', 'August'), ('SEPTEMBER', 'September'), ('OCTOBER', 'October'), ('NOVEMBER', 'November'), ('DECEMBER', 'December'), ('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('APRIL', 'April'), ('MAY', 'May'), ('JUNE', 'June')], default='JULY', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetline',
            name='monthly_activity_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='monthly_approved_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='monthly_proposed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='task_code',
            field=models.CharField(default='TASK-001', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetline',
            name='task_in_mtef',
            field=models.TextField(default='Default Task'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minutesheet',
            name='activity_series',
            field=models.TextField(blank=True, default='', help_text='List the series of activities to be carried out.'),
        ),
        migrations.AddField(
            model_name='minutesheet',
            name='director_approved_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='minutesheet',
            name='director_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='minutesheet',
            name='hou_recommended_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='minutesheet',
            name='requested_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='finance_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='finance.financerequest'),
        ),
        migrations.AlterField(
            model_name='financerequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('HOU_REVIEWED', 'HOU Reviewed'), ('DIRECTOR_APPROVED', 'Director Approved'), ('PARTIALLY_APPROVED', 'Partially Approved'), ('DISBURSED', 'Disbursed'), ('RETIRED', 'Retired'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='minutesheet',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('HOU_REVIEW', 'HOU Review'), ('DIRECTOR_REVIEW', 'Director Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='DRAFT', max_length=30),
        ),
    ]
