# Generated by Django 4.2.29 on 2026-04-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_budgetline_amount_disbursed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetline',
            name='task_code',
            field=models.CharField(default='TASK-001', max_length=50),
        ),
        migrations.AlterField(
            model_name='financerequest',
            name='financial_year',
            field=models.CharField(default='2025/2026', max_length=20),
        ),
    ]
