# Generated by Django 4.2.29 on 2026-04-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_budgetline_task_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
