# Generated by Django 4.2.29 on 2026-04-26 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_budgetline_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutesheet',
            name='budget_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minute_sheets', to='finance.budgetline'),
        ),
        migrations.AddField(
            model_name='minutesheet',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minutesheet',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='financial_year',
            field=models.CharField(default='2025/2026', max_length=20),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='item_name',
            field=models.CharField(default='General Activity', max_length=255),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='month',
            field=models.CharField(choices=[('JULY', 'July'), ('AUGUST', 'August'), ('SEPTEMBER', 'September'), ('OCTOBER', 'October'), ('NOVEMBER', 'November'), ('DECEMBER', 'December'), ('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('APRIL', 'April'), ('MAY', 'May'), ('JUNE', 'June')], default='JULY', max_length=20),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='task_in_mtef',
            field=models.TextField(default='Default Task'),
        ),
    ]
