# Generated by Django 4.2.29 on 2026-04-28 04:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_minutesheet_budget_line_minutesheet_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetline',
            name='monthly_approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='monthly_proposed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='minutesheet',
            name='activity_series',
            field=models.TextField(blank=True, default=''),
        ),
    ]
