# Generated by Django 4.2.29 on 2026-04-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_budgetline_monthly_approved_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financerequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('HOU_REVIEWED', 'HOU Reviewed'), ('DIRECTOR_APPROVED', 'Director Approved'), ('PARTIALLY_APPROVED', 'Partially Approved'), ('DISBURSED', 'Disbursed'), ('RETIRED', 'Retired'), ('REJECTED', 'Rejected')], default='Draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='minutesheet',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('HOU_REVIEW', 'HOU Review'), ('DIRECTOR_REVIEW', 'Director Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='Draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='retirement',
            name='retirement_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
