# Generated by Django 4.2.29 on 2026-04-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_financerequest_status_alter_minutesheet_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retirementline',
            name='reference_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
