# Generated by Django 4.2.29 on 2026-05-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_retirement_approved_at_retirement_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='retirement',
            name='supporting_file',
            field=models.FileField(blank=True, null=True, upload_to='finance/retirements/supporting_docs/'),
        ),
    ]
