# Generated by Django 4.2.29 on 2026-05-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_retirement_supporting_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retirement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned')], default='DRAFT', max_length=20),
        ),
    ]
