# Generated by Django 4.2.29 on 2026-07-13 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0010_userprofile_approval_role'),
        ('finance', '0012_alter_retirement_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financerequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='financerequest',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_requests', to='permits.department'),
        ),
        migrations.AddField(
            model_name='financerequest',
            name='department_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_requests', to='permits.departmentunit'),
        ),
        migrations.AddField(
            model_name='minutesheet',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_minute_sheets', to='permits.department'),
        ),
        migrations.AddField(
            model_name='minutesheet',
            name='department_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_minute_sheets', to='permits.departmentunit'),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='step_name',
            field=models.CharField(choices=[('HEAD_OF_UNIT', 'Head of Unit'), ('ASSISTANT_DIRECTOR', 'Assistant Director'), ('DIRECTOR', 'Director'), ('DIVISION_BUDGET_OFFICER', 'Division Budget Officer'), ('ACCOUNTANT', 'Accountant'), ('FINAL_APPROVER', 'Final Approver')], max_length=40),
        ),
        migrations.AlterField(
            model_name='financerequest',
            name='request_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='financerequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('HOU_REVIEWED', 'HOU Reviewed'), ('DIRECTOR_APPROVED', 'Director Approved'), ('PARTIALLY_APPROVED', 'Partially Approved'), ('DISBURSED', 'Disbursed'), ('RETIRED', 'Retired'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='minutesheet',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('HOU_REVIEW', 'HOU Review'), ('DIRECTOR_REVIEW', 'Director Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='DRAFT', max_length=30),
        ),
        migrations.AddIndex(
            model_name='financerequest',
            index=models.Index(fields=['department', 'status'], name='finance_fin_departm_c9cbae_idx'),
        ),
        migrations.AddIndex(
            model_name='financerequest',
            index=models.Index(fields=['submitted_by', 'status'], name='finance_fin_submitt_41d878_idx'),
        ),
        migrations.AddIndex(
            model_name='financerequest',
            index=models.Index(fields=['financial_year'], name='finance_fin_financi_ad1c52_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.UniqueConstraint(fields=('finance_request', 'sequence_no'), name='unique_finance_request_approval_sequence'),
        ),
    ]
