# Generated by Django 4.2.29 on 2026-07-13 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0010_userprofile_approval_role'),
        ('finance', '0013_alter_financerequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetline',
            options={'ordering': ['financial_year', 'month', 'task_code']},
        ),
        migrations.AddField(
            model_name='budgetline',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_budget_lines', to='permits.department'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='department_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_budget_lines', to='permits.departmentunit'),
        ),
        migrations.AddIndex(
            model_name='budgetline',
            index=models.Index(fields=['department', 'financial_year'], name='finance_bud_departm_cf7a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetline',
            index=models.Index(fields=['department', 'month'], name='finance_bud_departm_966877_idx'),
        ),
    ]
