# Generated by Django 4.2.29 on 2026-03-14 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalWorkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(blank=True, max_length=30, unique=True)),
                ('requester_name', models.CharField(blank=True, max_length=150)),
                ('requester_employee_id', models.CharField(blank=True, max_length=50)),
                ('purpose', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_group_request', models.BooleanField(default=False)),
                ('group_leader_name', models.CharField(blank=True, max_length=150)),
                ('group_leader_employee_id', models.CharField(blank=True, max_length=50)),
                ('acting_officer_name', models.CharField(blank=True, max_length=150)),
                ('acting_officer_employee_id', models.CharField(blank=True, max_length=50)),
                ('acting_officer_phone', models.CharField(blank=True, max_length=30)),
                ('unit_name', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('PENDING_HOU', 'Pending Head of Unit'), ('PENDING_DIRECTOR', 'Pending Director'), ('RETURNED_HOU', 'Returned by Head of Unit'), ('RETURNED_DIRECTOR', 'Returned by Director'), ('APPROVED', 'Approved'), ('REJECTED_HOU', 'Rejected by Head of Unit'), ('REJECTED_DIRECTOR', 'Rejected by Director'), ('CLOSED', 'Closed')], default='PENDING_DIRECTOR', max_length=30)),
                ('hou_comment', models.TextField(blank=True)),
                ('director_comment', models.TextField(blank=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('resubmitted_at', models.DateTimeField(blank=True, null=True)),
                ('hou_approved_at', models.DateTimeField(blank=True, null=True)),
                ('director_approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_by_role', models.CharField(blank=True, max_length=50)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('task_approval_file', models.FileField(blank=True, null=True, upload_to='task_approvals/')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_requests', to=settings.AUTH_USER_MODEL)),
                ('director_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_approved_requests', to=settings.AUTH_USER_MODEL)),
                ('head_of_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_of_unit_requests', to=settings.AUTH_USER_MODEL)),
                ('hou_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hou_approved_requests', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('REQUESTER', 'Requester'), ('ADMIN', 'Admin'), ('DIRECTOR', 'Director'), ('ADRD', 'ADRD'), ('ADSTI', 'ADSTI'), ('HEAD_OF_UNIT', 'Head of Unit')], default='REQUESTER', max_length=20)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('check_number', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('unit_name', models.CharField(blank=True, choices=[('KTIU', 'Knowledge Translation and Impact Unit'), ('IMCU', 'Infrastructure Management and Coordination Unit'), ('LSU', 'Linkage and Support Unit'), ('RICU', 'Regional and International Cooperation Unit'), ('DTSU', 'Digital Technologies and STEM Unit')], max_length=20, null=True)),
                ('head_of_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles_under_me', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='permits.externalworkrequest')),
            ],
        ),
    ]
