# Generated by Django 4.2.29 on 2026-03-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='unit_name',
            field=models.CharField(blank=True, choices=[('KTIU', 'Knowledge Translation and Impact Unit'), ('IMCU', 'Infrastructure Management and Coordination Unit'), ('LSU', 'Linkage and Support Unit'), ('RICU', 'Regional and International Cooperation Unit'), ('DTSU', 'Digital Technologies and STEM Unit'), ('CCU', 'Crosscutting Unit')], max_length=20, null=True),
        ),
    ]
