# Generated by Django 4.2.29 on 2026-03-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0002_alter_userprofile_unit_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalworkrequest',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='groupmember',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='externalworkrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='externalworkrequest',
            name='end_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='externalworkrequest',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='externalworkrequest',
            name='status',
            field=models.CharField(choices=[('PENDING_HOU', 'Pending Head of Unit'), ('PENDING_DIRECTOR', 'Pending Director'), ('RETURNED_HOU', 'Returned by Head of Unit'), ('RETURNED_DIRECTOR', 'Returned by Director'), ('APPROVED', 'Approved'), ('REJECTED_HOU', 'Rejected by Head of Unit'), ('REJECTED_DIRECTOR', 'Rejected by Director'), ('CLOSED', 'Closed')], db_index=True, default='PENDING_DIRECTOR', max_length=30),
        ),
        migrations.AlterField(
            model_name='externalworkrequest',
            name='unit_name',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='externalworkrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('REQUESTER', 'Requester'), ('ADMIN', 'Admin'), ('DIRECTOR', 'Director'), ('ADRD', 'ADRD'), ('ADSTI', 'ADSTI'), ('HEAD_OF_UNIT', 'Head of Unit')], db_index=True, default='REQUESTER', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='unit_name',
            field=models.CharField(blank=True, choices=[('KTIU', 'Knowledge Translation and Impact Unit'), ('IMCU', 'Infrastructure Management and Coordination Unit'), ('LSU', 'Linkage and Support Unit'), ('RICU', 'Regional and International Cooperation Unit'), ('DTSU', 'Digital Technologies and STEM Unit'), ('CCU', 'Crosscutting Unit')], db_index=True, max_length=20, null=True),
        ),
    ]
