# Generated by Django 4.2.29 on 2026-03-18 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permits', '0003_alter_externalworkrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalworkrequest',
            name='acting_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acting_officer_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
