# Generated by Django 4.2.29 on 2026-05-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0006_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('REQUESTER', 'Requester'), ('ADMIN', 'Admin'), ('DIRECTOR', 'Director'), ('ADRD', 'ADRD'), ('ADSTI', 'ADSTI'), ('HEAD_OF_UNIT', 'Head of Unit'), ('DBO', 'Division Budget Officer'), ('AC', 'Accountant')], db_index=True, default='REQUESTER', max_length=20),
        ),
    ]
