# Generated by Django 4.2.29 on 2026-07-05 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0008_department_departmentunit_userprofile_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('PERMIT', 'Permit'), ('TASK', 'Task'), ('FINANCE', 'Finance'), ('EVENT', 'Event Management')], max_length=30)),
                ('step_order', models.PositiveIntegerField()),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approval_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='permits.approvalrole')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='permits.department')),
            ],
            options={
                'ordering': ['department__code', 'module', 'step_order'],
                'unique_together': {('department', 'module', 'step_order')},
            },
        ),
    ]
