# Generated by Django 4.2.29 on 2026-07-05 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0009_approvalrole_departmentapprovalworkflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='approval_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='permits.approvalrole'),
        ),
    ]
