# Generated by Django 4.2.29 on 2026-07-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0010_userprofile_approval_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('REQUESTER', 'Requester'), ('ADMIN', 'Admin'), ('DIRECTOR', 'Director'), ('HEAD_OF_UNIT', 'Head of Unit'), ('ASSISTANT_DIRECTOR', 'Assistant Director'), ('DIVISION_BUDGET_OFFICER', 'Division Budget Officer'), ('ACCOUNTANT', 'Accountant')], default='REQUESTER', max_length=30),
        ),
    ]
