# Generated by Django 4.2.29 on 2026-08-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0011_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('REQUESTER', 'Requester'), ('ADMIN', 'Admin'), ('DIRECTOR', 'Director'), ('HEAD_OF_UNIT', 'Head of Unit'), ('ASSISTANT_DIRECTOR', 'Assistant Director'), ('DIVISION_BUDGET_OFFICER', 'Division Budget Officer'), ('ACCOUNTANT', 'Accountant'), ('EVENT_ADMIN', 'Event Administrator'), ('REGISTRATION_OFFICER', 'Event Registration Officer'), ('ATTENDANCE_OFFICER', 'Event Attendance Officer'), ('REPORT_OFFICER', 'Event Reports Officer')], default='REQUESTER', max_length=30),
        ),
    ]
