# Generated by Django 4.2.29 on 2026-08-18 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permits', '0012_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('EVENT', 'Event Management'), ('FINANCE', 'Financial Management'), ('TASK', 'Task Management')], max_length=20)),
                ('role_code', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_role_assignments', to='permits.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__username', 'module'),
            },
        ),
        migrations.AddConstraint(
            model_name='moduleroleassignment',
            constraint=models.UniqueConstraint(fields=('user', 'module'), name='unique_module_role_per_user'),
        ),
    ]
