# Generated by Django 4.2.29 on 2026-08-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0013_moduleroleassignment_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='moduleroleassignment',
            name='unique_module_role_per_user',
        ),
        migrations.AddConstraint(
            model_name='moduleroleassignment',
            constraint=models.UniqueConstraint(fields=('user', 'module', 'role_code'), name='unique_user_module_role'),
        ),
    ]
