from django.urls import path

from . import views


app_name = "meetings"

urlpatterns = [
    path("staff/meetings/", views.meeting_list, name="meeting_list"),
    path(
        "staff/meetings/my-workspace/",
        views.personal_meeting_workspace,
        name="personal_meeting_workspace",
    ),
    path(
        "staff/meetings/my-actions/<int:action_id>/update/",
        views.personal_action_update,
        name="personal_action_update",
    ),
    path(
        "staff/meetings/my-documents/<int:document_id>/download/",
        views.personal_document_download,
        name="personal_document_download",
    ),
    path(
        "staff/meetings/my-documents/<int:document_id>/acknowledge/",
        views.personal_document_acknowledge,
        name="personal_document_acknowledge",
    ),
    path(
        "staff/meetings/action-progress/<int:update_id>/evidence/",
        views.action_progress_evidence_download,
        name="action_progress_evidence_download",
    ),
    path(
        "staff/meetings/dashboard/",
        views.executive_dashboard,
        name="executive_dashboard",
    ),
    path(
        "staff/meetings/reports/decisions/",
        views.decision_register,
        name="decision_register",
    ),
    path(
        "staff/meetings/reports/decisions/export/",
        views.decision_register_csv,
        name="decision_register_csv",
    ),
    path(
        "staff/meetings/follow-up/",
        views.follow_up_center,
        name="follow_up_center",
    ),
    path(
        "staff/meetings/readiness/",
        views.readiness_center,
        name="readiness_center",
    ),
    path(
        "staff/meetings/action-reviews/",
        views.action_review_center,
        name="action_review_center",
    ),
    path(
        "staff/meetings/follow-up/actions/escalate-overdue/",
        views.action_escalation_bulk_send,
        name="action_escalation_bulk_send",
    ),
    path(
        "staff/meetings/calendar/",
        views.meeting_calendar,
        name="meeting_calendar",
    ),
    path("staff/meetings/resources/", views.resource_list, name="resource_list"),
    path(
        "staff/meetings/resources/new/",
        views.resource_create,
        name="resource_create",
    ),
    path(
        "staff/meetings/resources/<int:resource_id>/edit/",
        views.resource_edit,
        name="resource_edit",
    ),
    path("staff/meetings/series/", views.series_list, name="series_list"),
    path(
        "staff/meetings/series/new/",
        views.series_create,
        name="series_create",
    ),
    path(
        "staff/meetings/series/<int:series_id>/",
        views.series_detail,
        name="series_detail",
    ),
    path(
        "staff/meetings/series/<int:series_id>/edit/",
        views.series_edit,
        name="series_edit",
    ),
    path(
        "staff/meetings/series/<int:series_id>/agenda/add/",
        views.series_agenda_add,
        name="series_agenda_add",
    ),
    path(
        "staff/meetings/series/<int:series_id>/schedule/",
        views.series_occurrence_create,
        name="series_occurrence_create",
    ),
    path(
        "staff/meetings/reports/actions/",
        views.action_report,
        name="action_report",
    ),
    path(
        "staff/meetings/reports/actions/export/",
        views.action_report_csv,
        name="action_report_csv",
    ),
    path("staff/meetings/new/", views.meeting_create, name="meeting_create"),
    path(
        "staff/meetings/<int:meeting_id>/",
        views.meeting_detail,
        name="meeting_detail",
    ),
    path(
        "staff/meetings/<int:meeting_id>/edit/",
        views.meeting_edit,
        name="meeting_edit",
    ),
    path(
        "staff/meetings/<int:meeting_id>/print/",
        views.meeting_print,
        name="meeting_print",
    ),
    path(
        "staff/meetings/<int:meeting_id>/attendance/export/",
        views.attendance_register_csv,
        name="attendance_register_csv",
    ),
    path(
        "staff/meetings/<int:meeting_id>/feedback/export/",
        views.feedback_report_csv,
        name="feedback_report_csv",
    ),
    path(
        "staff/meetings/<int:meeting_id>/close/",
        views.meeting_close,
        name="meeting_close",
    ),
    path(
        "staff/meetings/<int:meeting_id>/reopen/",
        views.meeting_reopen,
        name="meeting_reopen",
    ),
    path(
        "staff/meetings/<int:meeting_id>/agenda/add/",
        views.agenda_add,
        name="agenda_add",
    ),
    path(
        "staff/meetings/<int:meeting_id>/resources/add/",
        views.resource_booking_add,
        name="resource_booking_add",
    ),
    path(
        "staff/meetings/<int:meeting_id>/resources/<int:booking_id>/update/",
        views.resource_booking_update,
        name="resource_booking_update",
    ),
    path(
        "staff/meetings/<int:meeting_id>/documents/add/",
        views.document_add,
        name="document_add",
    ),
    path(
        "staff/meetings/<int:meeting_id>/minutes/document/download/",
        views.minutes_document_download,
        name="minutes_document_download",
    ),
    path(
        "staff/meetings/<int:meeting_id>/documents/<int:document_id>/download/",
        views.document_download,
        name="document_download",
    ),
    path(
        "staff/meetings/<int:meeting_id>/documents/<int:document_id>/archive/",
        views.document_archive,
        name="document_archive",
    ),
    path(
        "staff/meetings/<int:meeting_id>/participants/add/",
        views.attendee_add,
        name="attendee_add",
    ),
    path(
        "staff/meetings/<int:meeting_id>/participants/<int:attendee_id>/update/",
        views.attendee_update,
        name="attendee_update",
    ),
    path(
        "staff/meetings/<int:meeting_id>/participants/<int:attendee_id>/pass/",
        views.attendee_pass,
        name="attendee_pass",
    ),
    path(
        "staff/meetings/<int:meeting_id>/participants/<int:attendee_id>/invite/",
        views.invitation_send,
        name="invitation_send",
    ),
    path(
        "staff/meetings/<int:meeting_id>/invitations/send-pending/",
        views.invitation_bulk_send,
        name="invitation_bulk_send",
    ),
    path(
        "staff/meetings/<int:meeting_id>/participants/<int:attendee_id>/remind/",
        views.rsvp_reminder_send,
        name="rsvp_reminder_send",
    ),
    path(
        "staff/meetings/<int:meeting_id>/invitations/remind-pending/",
        views.rsvp_reminder_bulk_send,
        name="rsvp_reminder_bulk_send",
    ),
    path(
        "staff/meetings/<int:meeting_id>/participants/remind-upcoming/",
        views.meeting_reminder_bulk_send,
        name="meeting_reminder_bulk_send",
    ),
    path(
        "staff/meetings/<int:meeting_id>/minutes/update/",
        views.minutes_update,
        name="minutes_update",
    ),
    path(
        "staff/meetings/<int:meeting_id>/minutes/submit/",
        views.minutes_submit,
        name="minutes_submit",
    ),
    path(
        "staff/meetings/<int:meeting_id>/minutes/approve/",
        views.minutes_approve,
        name="minutes_approve",
    ),
    path(
        "staff/meetings/<int:meeting_id>/minutes/return/",
        views.minutes_return,
        name="minutes_return",
    ),
    path(
        "staff/meetings/<int:meeting_id>/minutes/reopen/",
        views.minutes_reopen,
        name="minutes_reopen",
    ),
    path(
        "staff/meetings/<int:meeting_id>/decisions/add/",
        views.decision_add,
        name="decision_add",
    ),
    path(
        "staff/meetings/<int:meeting_id>/actions/add/",
        views.action_add,
        name="action_add",
    ),
    path(
        "staff/meetings/<int:meeting_id>/actions/<int:action_id>/update/",
        views.action_update,
        name="action_update",
    ),
    path(
        "staff/meetings/<int:meeting_id>/actions/<int:action_id>/completion-review/",
        views.action_completion_review,
        name="action_completion_review",
    ),
    path(
        "staff/meetings/<int:meeting_id>/actions/<int:action_id>/remind/",
        views.action_reminder_send,
        name="action_reminder_send",
    ),
    path(
        "staff/meetings/<int:meeting_id>/actions/remind-due/",
        views.action_reminder_bulk_send,
        name="action_reminder_bulk_send",
    ),
    path(
        "staff/meetings/<int:meeting_id>/actions/<int:action_id>/escalate/",
        views.action_escalation_send,
        name="action_escalation_send",
    ),
    path(
        "meetings/invitations/<uuid:response_token>/",
        views.invitation_response,
        name="invitation_response",
    ),
    path(
        "meetings/feedback/<uuid:response_token>/",
        views.meeting_feedback,
        name="meeting_feedback",
    ),
    path(
        "staff/meetings/check-in/<uuid:response_token>/",
        views.attendee_checkin,
        name="attendee_checkin",
    ),
]

