# Generated by Django 4.2.30 on 2026-08-07 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0007_event_participation_fee_event_payment_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('reference_number', models.CharField(help_text='Use the official meeting reference when available.', max_length=80, unique=True, verbose_name='meeting reference number')),
                ('meeting_type', models.CharField(choices=[('MANAGEMENT', 'Management meeting'), ('TECHNICAL', 'Technical meeting'), ('COMMITTEE', 'Committee meeting'), ('BOARD', 'Board meeting'), ('STAKEHOLDER', 'Stakeholder meeting'), ('WORKING_SESSION', 'Working session'), ('OTHER', 'Other meeting')], default='MANAGEMENT', max_length=30, verbose_name='meeting type')),
                ('chairperson_name', models.CharField(max_length=200, verbose_name='chairperson')),
                ('secretary_name', models.CharField(blank=True, max_length=200, verbose_name='meeting secretary')),
                ('quorum_required', models.PositiveIntegerField(blank=True, help_text='Leave empty when the meeting has no formal quorum.', null=True, verbose_name='required quorum')),
                ('invitation_deadline', models.DateTimeField(blank=True, null=True, verbose_name='invitation response deadline')),
                ('objectives_sw', models.TextField(blank=True, verbose_name='objectives in Kiswahili')),
                ('objectives_en', models.TextField(blank=True, verbose_name='objectives in English')),
                ('minutes_status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for approval'), ('APPROVED', 'Approved')], default='NOT_STARTED', max_length=20, verbose_name='minutes status')),
                ('minutes_sw', models.TextField(blank=True, verbose_name='minutes in Kiswahili')),
                ('minutes_en', models.TextField(blank=True, verbose_name='minutes in English')),
                ('minutes_document', models.FileField(blank=True, null=True, upload_to='meetings/minutes/%Y/%m/', verbose_name='signed minutes document')),
                ('minutes_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='minutes approved at')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='events.event', verbose_name='event')),
                ('minutes_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_meeting_minutes', to=settings.AUTH_USER_MODEL, verbose_name='minutes approved by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'meeting',
                'verbose_name_plural': 'meetings',
                'ordering': ['-event__starts_at', 'reference_number'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('item_number', models.PositiveIntegerField(verbose_name='agenda item number')),
                ('title_sw', models.CharField(max_length=300, verbose_name='agenda title in Kiswahili')),
                ('title_en', models.CharField(max_length=300, verbose_name='agenda title in English')),
                ('presenter_name', models.CharField(blank=True, max_length=200, verbose_name='presenter')),
                ('allocated_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='allocated minutes')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='meetings.meeting', verbose_name='meeting')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'meeting agenda item',
                'verbose_name_plural': 'meeting agenda items',
                'ordering': ['meeting', 'item_number'],
            },
        ),
        migrations.CreateModel(
            name='MeetingDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('decision_number', models.PositiveIntegerField(verbose_name='decision number')),
                ('decision_sw', models.TextField(verbose_name='decision in Kiswahili')),
                ('decision_en', models.TextField(blank=True, verbose_name='decision in English')),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('APPROVED', 'Approved'), ('DEFERRED', 'Deferred')], default='APPROVED', max_length=20, verbose_name='status')),
                ('agenda_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='meetings.meetingagendaitem', verbose_name='agenda item')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='meetings.meeting', verbose_name='meeting')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'meeting decision',
                'verbose_name_plural': 'meeting decisions',
                'ordering': ['meeting', 'decision_number'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('attendee_type', models.CharField(choices=[('INTERNAL', 'Internal participant'), ('EXTERNAL', 'External participant')], default='EXTERNAL', max_length=20, verbose_name='participant type')),
                ('full_name', models.CharField(max_length=200, verbose_name='full name')),
                ('organization', models.CharField(blank=True, max_length=250, verbose_name='organization')),
                ('designation', models.CharField(blank=True, max_length=150, verbose_name='designation')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='phone number')),
                ('response_status', models.CharField(choices=[('INVITED', 'Invited'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('TENTATIVE', 'Tentative')], default='INVITED', max_length=20, verbose_name='invitation response')),
                ('attendance_status', models.CharField(choices=[('NOT_MARKED', 'Not marked'), ('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused')], default='NOT_MARKED', max_length=20, verbose_name='attendance status')),
                ('invitation_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='invitation sent at')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='invitation responded at')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='checked in at')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='meetings.meeting', verbose_name='meeting')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='system user')),
            ],
            options={
                'verbose_name': 'meeting participant',
                'verbose_name_plural': 'meeting participants',
                'ordering': ['meeting', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='MeetingActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('action_number', models.PositiveIntegerField(verbose_name='action number')),
                ('description_sw', models.TextField(verbose_name='action in Kiswahili')),
                ('description_en', models.TextField(blank=True, verbose_name='action in English')),
                ('responsible_name', models.CharField(blank=True, max_length=200, verbose_name='responsible person')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='due date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='status')),
                ('progress_notes', models.TextField(blank=True, verbose_name='progress notes')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='meetings.meetingdecision', verbose_name='decision')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='meetings.meeting', verbose_name='meeting')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_action_items', to=settings.AUTH_USER_MODEL, verbose_name='responsible system user')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'meeting action item',
                'verbose_name_plural': 'meeting action items',
                'ordering': ['meeting', 'action_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='meetingdecision',
            constraint=models.UniqueConstraint(fields=('meeting', 'decision_number'), name='unique_decision_number_per_meeting'),
        ),
        migrations.AddIndex(
            model_name='meetingattendee',
            index=models.Index(fields=['meeting', 'attendance_status'], name='meeting_attendance_idx'),
        ),
        migrations.AddConstraint(
            model_name='meetingattendee',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('meeting', 'user'), name='unique_internal_attendee_per_meeting'),
        ),
        migrations.AddConstraint(
            model_name='meetingattendee',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('meeting', 'email'), name='unique_attendee_email_per_meeting'),
        ),
        migrations.AddConstraint(
            model_name='meetingagendaitem',
            constraint=models.UniqueConstraint(fields=('meeting', 'item_number'), name='unique_agenda_number_per_meeting'),
        ),
        migrations.AddIndex(
            model_name='meetingactionitem',
            index=models.Index(fields=['status', 'due_date'], name='meeting_action_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='meetingactionitem',
            constraint=models.UniqueConstraint(fields=('meeting', 'action_number'), name='unique_action_number_per_meeting'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['meeting_type', 'minutes_status'], name='meeting_type_minutes_idx'),
        ),
    ]

