# Generated by Django 4.2.30 on 2026-08-07 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import meetings.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0004_meeting_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('document_type', models.CharField(choices=[('MEETING_NOTICE', 'Meeting notice'), ('AGENDA_PAPER', 'Agenda paper'), ('PRESENTATION', 'Presentation'), ('SUPPORTING_DOCUMENT', 'Supporting document'), ('ATTENDANCE_REGISTER', 'Attendance register'), ('SIGNED_MINUTES', 'Signed minutes'), ('OTHER', 'Other document')], default='SUPPORTING_DOCUMENT', max_length=30, verbose_name='document type')),
                ('title_sw', models.CharField(max_length=300, verbose_name='document title in Kiswahili')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='document title in English')),
                ('description_sw', models.TextField(blank=True, verbose_name='description in Kiswahili')),
                ('description_en', models.TextField(blank=True, verbose_name='description in English')),
                ('file', models.FileField(max_length=500, upload_to=meetings.models.meeting_document_upload_path, verbose_name='document file')),
                ('original_filename', models.CharField(editable=False, max_length=255, verbose_name='original filename')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('is_confidential', models.BooleanField(default=True, help_text='Confidential files are available only inside the staff workspace.', verbose_name='confidential document')),
                ('agenda_item', models.ForeignKey(blank=True, help_text='Optionally link this document to an agenda item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='meetings.meetingagendaitem', verbose_name='agenda item')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='meetings.meeting', verbose_name='meeting')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'meeting document',
                'verbose_name_plural': 'meeting documents',
                'ordering': ['meeting', 'document_type', 'title_sw', '-version'],
                'indexes': [models.Index(fields=['meeting', 'document_type', 'is_active'], name='meeting_doc_type_idx')],
            },
        ),
    ]

