# Generated by Django 4.2.30 on 2026-08-07 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0005_meetingdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='minutes_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not started'), ('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for approval'), ('RETURNED', 'Returned for correction'), ('APPROVED', 'Approved')], default='NOT_STARTED', max_length=20, verbose_name='minutes status'),
        ),
        migrations.CreateModel(
            name='MeetingMinutesReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('action', models.CharField(choices=[('SUBMITTED', 'Submitted for approval'), ('RETURNED', 'Returned for correction'), ('APPROVED', 'Approved'), ('REOPENED', 'Reopened for correction')], max_length=20, verbose_name='review action')),
                ('comment', models.TextField(blank=True, verbose_name='review comment')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minutes_reviews', to='meetings.meeting', verbose_name='meeting')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'minutes review record',
                'verbose_name_plural': 'minutes review records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['meeting', 'action', 'created_at'], name='meeting_minutes_review_idx')],
            },
        ),
    ]

