# Generated by Django 4.2.30 on 2026-08-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_alter_meeting_minutes_status_meetingminutesreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='attendance_mode',
            field=models.CharField(choices=[('IN_PERSON', 'In-person meeting'), ('ONLINE', 'Online meeting'), ('HYBRID', 'Hybrid meeting')], default='IN_PERSON', max_length=20, verbose_name='meeting attendance mode'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='online_instructions_en',
            field=models.TextField(blank=True, verbose_name='online joining instructions in English'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='online_instructions_sw',
            field=models.TextField(blank=True, verbose_name='online joining instructions in Kiswahili'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='online_join_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='online joining link'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='online_meeting_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='online meeting ID'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='online_passcode',
            field=models.CharField(blank=True, max_length=120, verbose_name='online meeting passcode'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='online_platform',
            field=models.CharField(blank=True, choices=[('ZOOM', 'Zoom'), ('MICROSOFT_TEAMS', 'Microsoft Teams'), ('GOOGLE_MEET', 'Google Meet'), ('WEBEX', 'Cisco Webex'), ('OTHER', 'Other platform')], max_length=30, verbose_name='online meeting platform'),
        ),
        migrations.AddField(
            model_name='meetingseries',
            name='attendance_mode',
            field=models.CharField(choices=[('IN_PERSON', 'In-person meeting'), ('ONLINE', 'Online meeting'), ('HYBRID', 'Hybrid meeting')], default='IN_PERSON', max_length=20, verbose_name='default meeting attendance mode'),
        ),
        migrations.AddField(
            model_name='meetingseries',
            name='online_instructions_en',
            field=models.TextField(blank=True, verbose_name='default online joining instructions in English'),
        ),
        migrations.AddField(
            model_name='meetingseries',
            name='online_instructions_sw',
            field=models.TextField(blank=True, verbose_name='default online joining instructions in Kiswahili'),
        ),
        migrations.AddField(
            model_name='meetingseries',
            name='online_join_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='default online joining link'),
        ),
        migrations.AddField(
            model_name='meetingseries',
            name='online_meeting_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='default online meeting ID'),
        ),
        migrations.AddField(
            model_name='meetingseries',
            name='online_passcode',
            field=models.CharField(blank=True, max_length=120, verbose_name='default online meeting passcode'),
        ),
        migrations.AddField(
            model_name='meetingseries',
            name='online_platform',
            field=models.CharField(blank=True, choices=[('ZOOM', 'Zoom'), ('MICROSOFT_TEAMS', 'Microsoft Teams'), ('GOOGLE_MEET', 'Google Meet'), ('WEBEX', 'Cisco Webex'), ('OTHER', 'Other platform')], max_length=30, verbose_name='default online meeting platform'),
        ),
    ]

