# Generated by Django 4.2.30 on 2026-08-07 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0007_meeting_attendance_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='resource code')),
                ('name_sw', models.CharField(max_length=200, verbose_name='resource name in Kiswahili')),
                ('name_en', models.CharField(max_length=200, verbose_name='resource name in English')),
                ('description_sw', models.TextField(blank=True, verbose_name='description in Kiswahili')),
                ('description_en', models.TextField(blank=True, verbose_name='description in English')),
                ('total_quantity', models.PositiveIntegerField(default=1, verbose_name='available quantity')),
                ('storage_location', models.CharField(blank=True, max_length=250, verbose_name='storage location')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'meeting resource',
                'verbose_name_plural': 'meeting resources',
                'ordering': ['name_sw', 'code'],
            },
        ),
        migrations.CreateModel(
            name='MeetingResourceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity required')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Unavailable'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20, verbose_name='booking status')),
                ('notes', models.TextField(blank=True, verbose_name='booking notes')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmed at')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_meeting_resources', to=settings.AUTH_USER_MODEL, verbose_name='confirmed by')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_bookings', to='meetings.meeting', verbose_name='meeting')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='meetings.meetingresource', verbose_name='meeting resource')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'meeting resource booking',
                'verbose_name_plural': 'meeting resource bookings',
                'ordering': ['meeting', 'resource__name_sw'],
                'indexes': [models.Index(fields=['resource', 'status', 'is_active'], name='meeting_resource_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='meetingresourcebooking',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('status__in', ['REQUESTED', 'CONFIRMED'])), fields=('meeting', 'resource'), name='unique_active_resource_per_meeting'),
        ),
    ]

