# Generated by Django 4.2.30 on 2026-08-10 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0008_meetingresource_meetingresourcebooking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='checkin_closes_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='check-in closes at'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='checkin_enabled',
            field=models.BooleanField(default=False, verbose_name='meeting QR check-in enabled'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='checkin_opens_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='check-in opens at'),
        ),
        migrations.AddField(
            model_name='meetingattendee',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_participant_checkins', to=settings.AUTH_USER_MODEL, verbose_name='checked in by'),
        ),
        migrations.AddField(
            model_name='meetingattendee',
            name='checkin_method',
            field=models.CharField(blank=True, choices=[('QR', 'QR scan'), ('MANUAL', 'Manual attendance update')], max_length=20, verbose_name='meeting check-in method'),
        ),
    ]

