# Generated by Django 4.2.30 on 2026-08-10 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0009_meeting_checkin_closes_at_meeting_checkin_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='meeting closed at'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_meetings', to=settings.AUTH_USER_MODEL, verbose_name='meeting closed by'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='closure_status',
            field=models.CharField(choices=[('OPEN', 'Open for post-meeting work'), ('CLOSED', 'Formally closed')], default='OPEN', max_length=20, verbose_name='meeting closure status'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='closure_summary_en',
            field=models.TextField(blank=True, verbose_name='closure summary in English'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='closure_summary_sw',
            field=models.TextField(blank=True, verbose_name='closure summary in Kiswahili'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='evaluation_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='evaluation deadline'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='evaluation_enabled',
            field=models.BooleanField(default=False, verbose_name='participant evaluation enabled'),
        ),
        migrations.CreateModel(
            name='MeetingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('organization_rating', models.PositiveSmallIntegerField(choices=[(1, 'Very poor'), (2, 'Poor'), (3, 'Satisfactory'), (4, 'Good'), (5, 'Excellent')], verbose_name='organization and logistics rating')),
                ('content_rating', models.PositiveSmallIntegerField(choices=[(1, 'Very poor'), (2, 'Poor'), (3, 'Satisfactory'), (4, 'Good'), (5, 'Excellent')], verbose_name='agenda and content rating')),
                ('facilitation_rating', models.PositiveSmallIntegerField(choices=[(1, 'Very poor'), (2, 'Poor'), (3, 'Satisfactory'), (4, 'Good'), (5, 'Excellent')], verbose_name='chairing and facilitation rating')),
                ('venue_platform_rating', models.PositiveSmallIntegerField(choices=[(1, 'Very poor'), (2, 'Poor'), (3, 'Satisfactory'), (4, 'Good'), (5, 'Excellent')], verbose_name='venue or online platform rating')),
                ('overall_rating', models.PositiveSmallIntegerField(choices=[(1, 'Very poor'), (2, 'Poor'), (3, 'Satisfactory'), (4, 'Good'), (5, 'Excellent')], verbose_name='overall meeting rating')),
                ('comments', models.TextField(blank=True, verbose_name='feedback comments')),
                ('recommendations', models.TextField(blank=True, verbose_name='recommendations for future meetings')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='hide my identity in staff feedback reports')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='feedback submitted at')),
                ('attendee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='meetings.meetingattendee', verbose_name='meeting participant')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_responses', to='meetings.meeting', verbose_name='meeting')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'meeting feedback',
                'verbose_name_plural': 'meeting feedback',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['meeting', 'submitted_at'], name='meeting_feedback_date_idx')],
            },
        ),
    ]

