# Generated by Django 4.2.30 on 2026-08-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_meeting_closed_at_meeting_closed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingcommunicationlog',
            name='communication_type',
            field=models.CharField(choices=[('INVITATION', 'Meeting invitation'), ('RSVP_REMINDER', 'Attendance confirmation reminder'), ('MEETING_REMINDER', 'Upcoming meeting reminder'), ('ACTION_REMINDER', 'Action deadline reminder'), ('ACTION_ESCALATION', 'Overdue action escalation')], max_length=30, verbose_name='communication type'),
        ),
    ]

