# Generated by Django 4.2.30 on 2026-08-10 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0011_alter_meetingcommunicationlog_communication_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingDocumentAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('acknowledged_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='acknowledged at')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_acknowledgements', to='meetings.meetingattendee', verbose_name='meeting participant')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='meetings.meetingdocument', verbose_name='meeting document')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'meeting document acknowledgement',
                'verbose_name_plural': 'meeting document acknowledgements',
                'ordering': ['-acknowledged_at'],
                'indexes': [models.Index(fields=['document', 'acknowledged_at'], name='meeting_document_ack_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='meetingdocumentacknowledgement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('document', 'attendee'), name='unique_active_meeting_document_ack'),
        ),
    ]

