# Generated by Django 4.2.30 on 2026-08-10 11:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import meetings.models


def set_completed_action_progress(apps, schema_editor):
    MeetingActionItem = apps.get_model('meetings', 'MeetingActionItem')
    MeetingActionItem.objects.filter(status='COMPLETED').update(
        completion_percentage=100,
    )


def reverse_completed_action_progress(apps, schema_editor):
    MeetingActionItem = apps.get_model('meetings', 'MeetingActionItem')
    MeetingActionItem.objects.filter(status='COMPLETED').update(
        completion_percentage=0,
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0012_meetingdocumentacknowledgement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingactionitem',
            name='completion_percentage',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='completion percentage'),
        ),
        migrations.RunPython(
            set_completed_action_progress,
            reverse_completed_action_progress,
        ),
        migrations.CreateModel(
            name='MeetingActionProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], max_length=20, verbose_name='status')),
                ('completion_percentage', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='completion percentage')),
                ('notes', models.TextField(blank=True, verbose_name='progress update')),
                ('evidence_file', models.FileField(blank=True, max_length=500, upload_to=meetings.models.meeting_action_evidence_upload_path, verbose_name='supporting evidence')),
                ('original_filename', models.CharField(blank=True, editable=False, max_length=255, verbose_name='original filename')),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='reported at')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='meetings.meetingactionitem', verbose_name='meeting action item')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'meeting action progress update',
                'verbose_name_plural': 'meeting action progress updates',
                'ordering': ['-reported_at', '-created_at'],
                'indexes': [models.Index(fields=['action', 'reported_at'], name='meeting_action_progress_idx')],
            },
        ),
    ]

