# Generated by Django 4.2.30 on 2026-08-10 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0013_meetingactionitem_completion_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingactionitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('AWAITING_REVIEW', 'Awaiting completion review'), ('RETURNED', 'Returned for correction'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='meetingactionprogressupdate',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('AWAITING_REVIEW', 'Awaiting completion review'), ('RETURNED', 'Returned for correction'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], max_length=20, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='MeetingActionCompletionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('outcome', models.CharField(choices=[('VERIFIED', 'Completion verified'), ('RETURNED', 'Returned for correction')], max_length=20, verbose_name='review outcome')),
                ('comment', models.TextField(blank=True, verbose_name='review comment')),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='reviewed at')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_reviews', to='meetings.meetingactionitem', verbose_name='meeting action item')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'meeting action completion review',
                'verbose_name_plural': 'meeting action completion reviews',
                'ordering': ['-reviewed_at', '-created_at'],
                'indexes': [models.Index(fields=['action', 'reviewed_at'], name='meeting_action_review_idx')],
            },
        ),
    ]

