from django.urls import path

from . import views
from . import department_views


app_name = "forms_builder"

urlpatterns = [
    path(
        "manage/<slug:event_slug>/questionnaires/",
        department_views.questionnaire_list,
        name="questionnaire_list",
    ),
    path(
        "manage/<slug:event_slug>/questionnaires/new/",
        department_views.questionnaire_create,
        name="questionnaire_create",
    ),
    path(
        "manage/<slug:event_slug>/questionnaires/<int:form_id>/",
        department_views.questionnaire_builder,
        name="questionnaire_builder",
    ),
    path(
        "manage/<slug:event_slug>/questionnaires/<int:form_id>/settings/",
        department_views.questionnaire_edit,
        name="questionnaire_edit",
    ),
    path(
        "manage/<slug:event_slug>/questionnaires/<int:form_id>/print/",
        department_views.questionnaire_print,
        name="questionnaire_print",
    ),
    path(
        "manage/<slug:event_slug>/questionnaires/<int:form_id>/publish/",
        department_views.questionnaire_publish,
        name="questionnaire_publish",
    ),
    path(
        "manage/<slug:event_slug>/questionnaires/<int:form_id>/logic/<str:target_type>/<int:target_id>/",
        department_views.logic_editor,
        name="logic_editor",
    ),
    path(
        "manage/<slug:event_slug>/questionnaires/<int:form_id>/logic/<str:target_type>/<int:target_id>/rules/new/",
        department_views.logic_rule_edit,
        name="logic_rule_create",
    ),
    path(
        "manage/<slug:event_slug>/questionnaires/<int:form_id>/logic/<str:target_type>/<int:target_id>/rules/<int:rule_id>/",
        department_views.logic_rule_edit,
        name="logic_rule_edit",
    ),
    path(
        "manage/<slug:event_slug>/questionnaires/<int:form_id>/logic/<str:target_type>/<int:target_id>/rules/<int:rule_id>/archive/",
        department_views.logic_rule_archive,
        name="logic_rule_archive",
    ),
    path(
        "manage/<slug:event_slug>/questionnaires/<int:form_id>/logic/<str:target_type>/<int:target_id>/groups/new/",
        department_views.logic_group_create,
        name="logic_group_create",
    ),
    path(
        "manage/<slug:event_slug>/questionnaires/<int:form_id>/logic/<str:target_type>/<int:target_id>/groups/<int:group_id>/archive/",
        department_views.logic_group_archive,
        name="logic_group_archive",
    ),
    path(
        "manage/<slug:event_slug>/questionnaires/<int:form_id>/sections/new/",
        department_views.section_edit,
        name="section_create",
    ),
    path(
        "manage/<slug:event_slug>/questionnaires/<int:form_id>/sections/<int:section_id>/",
        department_views.section_edit,
        name="section_edit",
    ),
    path(
        "manage/<slug:event_slug>/questionnaires/<int:form_id>/sections/<int:section_id>/questions/new/",
        department_views.question_edit,
        name="question_create",
    ),
    path(
        "manage/<slug:event_slug>/questionnaires/<int:form_id>/sections/<int:section_id>/questions/<int:question_id>/",
        department_views.question_edit,
        name="question_edit",
    ),
    path(
        "manage/<slug:event_slug>/questionnaires/<int:form_id>/questions/<int:question_id>/options/new/",
        department_views.option_edit,
        name="option_create",
    ),
    path(
        "manage/<slug:event_slug>/questionnaires/<int:form_id>/questions/<int:question_id>/options/<int:option_id>/",
        department_views.option_edit,
        name="option_edit",
    ),
    path(
        "manage/<slug:event_slug>/questionnaires/<int:form_id>/<str:component>/<int:component_id>/<str:action>/",
        department_views.component_action,
        name="component_action",
    ),
    path(
        "participants/<uuid:participant_token>/",
        views.participant_portal,
        name="participant_portal",
    ),
    path(
        "events/<slug:event_slug>/booths/",
        views.booth_directory,
        name="booth_directory",
    ),
    path(
        "booths/<uuid:public_token>/",
        views.booth_detail,
        name="booth_detail",
    ),
    path(
        "booths/<uuid:public_token>/qr/",
        views.booth_qr,
        name="booth_qr",
    ),
    path(
        "reports/evaluations/",
        views.evaluation_reports,
        name="evaluation_reports",
    ),
    path(
        "reports/evaluations/export/",
        views.evaluation_report_csv,
        name="evaluation_reports_csv",
    ),
    path(
        "certificates/verify/<uuid:participant_token>/",
        views.certificate_verification,
        name="certificate_verification",
    ),
    path(
        "participants/<uuid:participant_token>/certificate/",
        views.participant_certificate,
        name="participant_certificate",
    ),
    path(
        "participants/<uuid:participant_token>/certificate/pdf/",
        views.participant_certificate_pdf,
        name="participant_certificate_pdf",
    ),
    path(
        "participants/<uuid:participant_token>/certificate/qr/",
        views.participant_certificate_qr,
        name="participant_certificate_qr",
    ),
    path(
        "participants/<uuid:participant_token>/badge/",
        views.participant_badge,
        name="participant_badge",
    ),
    path(
        "participants/<uuid:participant_token>/payment/",
        views.participant_payment,
        name="participant_payment",
    ),
    path(
        "participants/<uuid:participant_token>/payment/receipt/",
        views.payment_receipt,
        name="payment_receipt",
    ),
    path(
        "payments/<uuid:participant_token>/<int:payment_id>/verify/",
        views.payment_receipt_verification,
        name="payment_receipt_verification",
    ),
    path(
        "payments/<uuid:participant_token>/<int:payment_id>/qr/",
        views.payment_receipt_qr,
        name="payment_receipt_qr",
    ),
    path(
        "participants/<uuid:participant_token>/badge/qr/",
        views.participant_badge_qr,
        name="participant_badge_qr",
    ),
    path(
        "registration-status/",
        views.registration_status,
        name="registration_status",
    ),
    path(
        "events/<slug:event_slug>/forms/<slug:form_slug>/",
        views.public_event_form,
        name="public_event_form",
    ),
    path(
        "submissions/<str:reference_number>/success/",
        views.submission_success,
        name="submission_success",
    ),
]
