# Generated by Django 4.2.30 on 2026-07-24 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name_sw', models.CharField(max_length=200, verbose_name='form name in Kiswahili')),
                ('name_en', models.CharField(max_length=200, verbose_name='form name in English')),
                ('form_type', models.CharField(choices=[('REGISTRATION', 'Registration Form'), ('EVALUATION', 'Evaluation Form'), ('EXHIBITOR', 'Exhibitor Form'), ('SPEAKER', 'Speaker Application Form'), ('ATTENDANCE', 'Attendance Confirmation Form'), ('OTHER', 'Other Form')], default='REGISTRATION', max_length=30, verbose_name='form type')),
                ('slug', models.SlugField(blank=True, max_length=250, verbose_name='slug')),
                ('introduction_sw', models.TextField(blank=True, verbose_name='introduction in Kiswahili')),
                ('introduction_en', models.TextField(blank=True, verbose_name='introduction in English')),
                ('success_message_sw', models.TextField(blank=True, default='Taarifa zako zimepokelewa kwa mafanikio.', verbose_name='success message in Kiswahili')),
                ('success_message_en', models.TextField(blank=True, default='Your information has been submitted successfully.', verbose_name='success message in English')),
                ('opens_at', models.DateTimeField(blank=True, null=True, verbose_name='form opens')),
                ('closes_at', models.DateTimeField(blank=True, null=True, verbose_name='form closes')),
                ('requires_login', models.BooleanField(default=False, verbose_name='requires login')),
                ('allow_multiple_submissions', models.BooleanField(default=False, verbose_name='allow multiple submissions')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='events.event', verbose_name='event')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'event form',
                'verbose_name_plural': 'event forms',
                'ordering': ['event', 'form_type', 'name_sw'],
            },
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('label_sw', models.CharField(max_length=300, verbose_name='question in Kiswahili')),
                ('label_en', models.CharField(max_length=300, verbose_name='question in English')),
                ('question_type', models.CharField(choices=[('SHORT_TEXT', 'Short text'), ('LONG_TEXT', 'Long text'), ('EMAIL', 'Email address'), ('PHONE', 'Phone number'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('DATETIME', 'Date and time'), ('SINGLE_CHOICE', 'Single choice'), ('MULTIPLE_CHOICE', 'Multiple choice'), ('DROPDOWN', 'Dropdown'), ('YES_NO', 'Yes or No'), ('FILE', 'File upload'), ('IMAGE', 'Image upload')], default='SHORT_TEXT', max_length=30, verbose_name='question type')),
                ('help_text_sw', models.CharField(blank=True, max_length=300, verbose_name='help text in Kiswahili')),
                ('help_text_en', models.CharField(blank=True, max_length=300, verbose_name='help text in English')),
                ('placeholder_sw', models.CharField(blank=True, max_length=200, verbose_name='placeholder in Kiswahili')),
                ('placeholder_en', models.CharField(blank=True, max_length=200, verbose_name='placeholder in English')),
                ('is_required', models.BooleanField(default=False, verbose_name='required')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('minimum_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='minimum length')),
                ('maximum_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='maximum length')),
                ('minimum_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='minimum value')),
                ('maximum_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='maximum value')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'form question',
                'verbose_name_plural': 'form questions',
                'ordering': ['section', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('value', models.CharField(max_length=100, verbose_name='stored value')),
                ('label_sw', models.CharField(max_length=200, verbose_name='option in Kiswahili')),
                ('label_en', models.CharField(max_length=200, verbose_name='option in English')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='forms_builder.formquestion', verbose_name='question')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'question option',
                'verbose_name_plural': 'question options',
                'ordering': ['question', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title_sw', models.CharField(max_length=200, verbose_name='section title in Kiswahili')),
                ('title_en', models.CharField(max_length=200, verbose_name='section title in English')),
                ('description_sw', models.TextField(blank=True, verbose_name='section description in Kiswahili')),
                ('description_en', models.TextField(blank=True, verbose_name='section description in English')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('event_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='forms_builder.eventform', verbose_name='event form')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'form section',
                'verbose_name_plural': 'form sections',
                'ordering': ['event_form', 'display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='formquestion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='forms_builder.formsection', verbose_name='form section'),
        ),
        migrations.AddField(
            model_name='formquestion',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question', 'value'), name='unique_option_value_per_question'),
        ),
        migrations.AddConstraint(
            model_name='eventform',
            constraint=models.UniqueConstraint(fields=('event', 'slug'), name='unique_form_slug_per_event'),
        ),
    ]

