# Generated by Django 4.2.30 on 2026-07-24 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms_builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('reference_number', models.CharField(blank=True, max_length=60, unique=True, verbose_name='reference number')),
                ('language', models.CharField(choices=[('sw', 'Kiswahili'), ('en', 'English')], default='sw', max_length=5, verbose_name='submission language')),
                ('submitter_email', models.EmailField(blank=True, max_length=254, verbose_name='submitter email')),
                ('submitter_phone', models.CharField(blank=True, max_length=30, verbose_name='submitter phone')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('is_complete', models.BooleanField(default=True, verbose_name='complete submission')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('event_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms_builder.eventform', verbose_name='event form')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_form_submissions', to=settings.AUTH_USER_MODEL, verbose_name='submitted by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'form submission',
                'verbose_name_plural': 'form submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('text_value', models.TextField(blank=True, verbose_name='text value')),
                ('number_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='number value')),
                ('date_value', models.DateField(blank=True, null=True, verbose_name='date value')),
                ('datetime_value', models.DateTimeField(blank=True, null=True, verbose_name='date and time value')),
                ('boolean_value', models.BooleanField(blank=True, null=True, verbose_name='boolean value')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='form_submissions/files/', verbose_name='uploaded file')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='forms_builder.formquestion', verbose_name='question')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='answers', to='forms_builder.questionoption', verbose_name='selected options')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forms_builder.formsubmission', verbose_name='submission')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'form answer',
                'verbose_name_plural': 'form answers',
                'ordering': ['submission', 'question__display_order'],
            },
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['event_form', 'created_at'], name='form_submit_created_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['reference_number'], name='form_submit_ref_idx'),
        ),
        migrations.AddConstraint(
            model_name='formanswer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='unique_answer_per_submission_question'),
        ),
    ]

