# Generated by Django 4.2.30 on 2026-07-25 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms_builder', '0002_formsubmission_formanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='review_notes',
            field=models.TextField(blank=True, help_text='Visible to administrators only. Do not include passwords or secrets.', verbose_name='internal review notes'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20, verbose_name='review status'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='reviewed at'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_form_submissions', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by'),
        ),
    ]

