# Generated by Django 4.2.30 on 2026-07-27 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_remove_event_organizer_name'),
        ('forms_builder', '0006_update_badge_representative_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(help_text='For example A-01 or HALL-B-12.', max_length=30, verbose_name='booth code')),
                ('name_sw', models.CharField(max_length=200, verbose_name='booth name in Kiswahili')),
                ('name_en', models.CharField(max_length=200, verbose_name='booth name in English')),
                ('zone_sw', models.CharField(blank=True, max_length=150, verbose_name='zone or location in Kiswahili')),
                ('zone_en', models.CharField(blank=True, max_length=150, verbose_name='zone or location in English')),
                ('status', models.CharField(choices=[('UNASSIGNED', 'Unassigned'), ('ASSIGNED', 'Assigned'), ('READY', 'Ready'), ('CLOSED', 'Closed')], default='UNASSIGNED', max_length=20, verbose_name='booth setup status')),
                ('notes', models.TextField(blank=True, verbose_name='internal booth notes')),
                ('assigned_submission', models.OneToOneField(blank=True, help_text='Only an approved submission from this event may be assigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booth_assignment', to='forms_builder.formsubmission', verbose_name='assigned exhibitor submission')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booths', to='events.event', verbose_name='event')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'booth',
                'verbose_name_plural': 'booths',
                'ordering': ['event', 'zone_en', 'code'],
            },
        ),
        migrations.AddConstraint(
            model_name='booth',
            constraint=models.UniqueConstraint(fields=('event', 'code'), name='unique_booth_code_per_event'),
        ),
    ]

