# Generated by Django 4.2.30 on 2026-07-29 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms_builder', '0008_booth_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='public booth description in English'),
        ),
        migrations.AddField(
            model_name='booth',
            name='description_sw',
            field=models.TextField(blank=True, verbose_name='public booth description in Kiswahili'),
        ),
        migrations.AddField(
            model_name='booth',
            name='public_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='public booth email'),
        ),
        migrations.AddField(
            model_name='booth',
            name='public_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='public booth phone'),
        ),
        migrations.AddField(
            model_name='booth',
            name='public_website',
            field=models.URLField(blank=True, verbose_name='public booth website'),
        ),
        migrations.CreateModel(
            name='BoothOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('offering_type', models.CharField(choices=[('PRODUCT', 'Product'), ('TECHNOLOGY', 'Technology'), ('SERVICE', 'Service'), ('OTHER', 'Other')], default='PRODUCT', max_length=20, verbose_name='offering type')),
                ('name_sw', models.CharField(max_length=200, verbose_name='offering name in Kiswahili')),
                ('name_en', models.CharField(max_length=200, verbose_name='offering name in English')),
                ('description_sw', models.TextField(blank=True, verbose_name='offering description in Kiswahili')),
                ('description_en', models.TextField(blank=True, verbose_name='offering description in English')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='forms_builder.booth', verbose_name='booth')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'booth offering',
                'verbose_name_plural': 'booth offerings',
                'ordering': ['booth', 'display_order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='BoothInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('visitor_name', models.CharField(blank=True, max_length=200, verbose_name='visitor name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='visitor email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='visitor phone')),
                ('message', models.TextField(blank=True, verbose_name='visitor message')),
                ('language', models.CharField(choices=[('sw', 'Kiswahili'), ('en', 'English')], default='sw', max_length=5, verbose_name='language')),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='forms_builder.booth', verbose_name='booth')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interests', to='forms_builder.boothoffering', verbose_name='offering of interest')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'booth visitor interest',
                'verbose_name_plural': 'booth visitor interests',
                'ordering': ['-created_at'],
            },
        ),
    ]

