# Generated by Django 4.2.30 on 2026-07-29 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms_builder', '0009_booth_description_en_booth_description_sw_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('notification_type', models.CharField(choices=[('REGISTRATION_RECEIVED', 'Registration received'), ('REGISTRATION_APPROVED', 'Registration approved'), ('REGISTRATION_REJECTED', 'Registration rejected'), ('CHECK_IN_CONFIRMED', 'Check-in confirmed')], max_length=40, verbose_name='notification type')),
                ('recipient', models.EmailField(blank=True, max_length=254, verbose_name='recipient email')),
                ('subject', models.CharField(blank=True, max_length=250, verbose_name='email subject')),
                ('delivery_status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='SKIPPED', max_length=20, verbose_name='delivery status')),
                ('error_message', models.TextField(blank=True, verbose_name='delivery error')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='forms_builder.formsubmission', verbose_name='form submission')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'notification log',
                'verbose_name_plural': 'notification logs',
                'ordering': ['-created_at'],
            },
        ),
    ]

