# Generated by Django 4.2.30 on 2026-07-29 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_organizer_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms_builder', '0010_notificationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('REGISTRATION_RECEIVED', 'Registration received'), ('REGISTRATION_APPROVED', 'Registration approved'), ('REGISTRATION_REJECTED', 'Registration rejected'), ('CHECK_IN_CONFIRMED', 'Check-in confirmed'), ('EVENT_REMINDER', 'Event reminder')], max_length=40, verbose_name='notification type'),
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('subject_sw', models.CharField(max_length=250, verbose_name='reminder subject in Kiswahili')),
                ('subject_en', models.CharField(max_length=250, verbose_name='reminder subject in English')),
                ('message_sw', models.TextField(verbose_name='reminder message in Kiswahili')),
                ('message_en', models.TextField(verbose_name='reminder message in English')),
                ('scheduled_for', models.DateTimeField(db_index=True, verbose_name='scheduled sending time')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed')], db_index=True, default='DRAFT', max_length=20, verbose_name='reminder status')),
                ('sent_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='sent count')),
                ('skipped_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='skipped count')),
                ('failed_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='failed count')),
                ('processed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='processed at')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_reminders', to='events.event', verbose_name='event')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'event reminder',
                'verbose_name_plural': 'event reminders',
                'ordering': ['-scheduled_for'],
            },
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='event_reminder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='forms_builder.eventreminder', verbose_name='event reminder'),
        ),
    ]

