# Generated by Django 4.2.30 on 2026-08-02 07:34

from django.db import migrations, models


def hide_exhibition_registration_summary(apps, schema_editor):
    EventForm = apps.get_model("forms_builder", "EventForm")
    EventForm.objects.filter(
        slug="exhibition-participant-registration-form",
    ).update(show_event_summary=False)


def show_exhibition_registration_summary(apps, schema_editor):
    EventForm = apps.get_model("forms_builder", "EventForm")
    EventForm.objects.filter(
        slug="exhibition-participant-registration-form",
    ).update(show_event_summary=True)


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0011_alter_notificationlog_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventform',
            name='show_event_summary',
            field=models.BooleanField(default=True, help_text='Display the event logo, code, title, dates and venue above this form.', verbose_name='show event summary above form'),
        ),
        migrations.RunPython(
            hide_exhibition_registration_summary,
            show_exhibition_registration_summary,
        ),
    ]

