# Generated by Django 4.2.30 on 2026-08-04 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0012_eventform_show_event_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsection',
            name='condition_question',
            field=models.ForeignKey(blank=True, help_text='Leave blank to always show this section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditional_sections', to='forms_builder.formquestion', verbose_name='show when question'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='condition_value',
            field=models.CharField(blank=True, help_text='Use the stored value of the controlling question option.', max_length=100, verbose_name='show when answer contains'),
        ),
    ]

