# Generated by Django 4.2.30 on 2026-08-04 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms_builder', '0014_configure_participation_skip_logic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='amount')),
                ('currency', models.CharField(default='TZS', max_length=3, verbose_name='currency')),
                ('method', models.CharField(choices=[('BANK', 'Bank deposit or transfer'), ('MOBILE', 'Mobile money'), ('CASH', 'Cash'), ('OTHER', 'Other')], default='BANK', max_length=20, verbose_name='payment method')),
                ('transaction_reference', models.CharField(blank=True, max_length=100, verbose_name='transaction reference')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('proof', models.FileField(blank=True, upload_to='payments/%Y/%m/', verbose_name='payment proof')),
                ('status', models.CharField(choices=[('PENDING', 'Pending verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20, verbose_name='payment status')),
                ('verified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='verified at')),
                ('notes', models.TextField(blank=True, verbose_name='payment notes')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='forms_builder.formsubmission', verbose_name='participant submission')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('verified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL, verbose_name='verified by')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-paid_at', '-created_at'],
            },
        ),
    ]

