# Generated by Django 4.2.30 on 2026-08-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0015_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateRecord',
            fields=[
            ],
            options={
                'verbose_name': 'certificate',
                'verbose_name_plural': 'certificates',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('forms_builder.formsubmission',),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
            ],
            options={
                'verbose_name': 'participant',
                'verbose_name_plural': 'participants',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('forms_builder.formsubmission',),
        ),
    ]

