# Generated by Django 4.2.30 on 2026-08-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0016_certificaterecord_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('REGISTRATION_RECEIVED', 'Registration received'), ('REGISTRATION_APPROVED', 'Registration approved'), ('REGISTRATION_REJECTED', 'Registration rejected'), ('CHECK_IN_CONFIRMED', 'Check-in confirmed'), ('EVENT_REMINDER', 'Event reminder'), ('PAYMENT_RECEIVED', 'Payment received'), ('PAYMENT_VERIFIED', 'Payment verified'), ('PAYMENT_REJECTED', 'Payment rejected')], max_length=40, verbose_name='notification type'),
        ),
    ]

