# Generated by Django 4.2.30 on 2026-08-04 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_participation_fee_event_payment_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms_builder', '0017_alter_notificationlog_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityPricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('first_unit_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='first unit price')),
                ('additional_unit_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='each additional unit price')),
                ('currency', models.CharField(default='TZS', max_length=3, verbose_name='currency')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_pricing_rule', to='events.event', verbose_name='event')),
                ('quantity_question', models.ForeignKey(help_text='Select the numeric question that determines the quantity.', on_delete=django.db.models.deletion.PROTECT, related_name='pricing_rules', to='forms_builder.formquestion', verbose_name='quantity question')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'quantity pricing rule',
                'verbose_name_plural': 'quantity pricing rules',
            },
        ),
    ]

