# Generated by Django 4.2.30 on 2026-08-05 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms_builder', '0019_configure_elimu_booth_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='certificate_authorized',
            field=models.BooleanField(db_index=True, default=False, verbose_name='certificate issuance authorized'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='certificate_authorized_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='certificate authorized at'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='certificate_authorized_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_participant_certificates', to=settings.AUTH_USER_MODEL, verbose_name='certificate authorized by'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('REGISTRATION_RECEIVED', 'Registration received'), ('REGISTRATION_APPROVED', 'Registration approved'), ('REGISTRATION_REJECTED', 'Registration rejected'), ('CHECK_IN_CONFIRMED', 'Check-in confirmed'), ('EVENT_REMINDER', 'Event reminder'), ('PAYMENT_RECEIVED', 'Payment received'), ('PAYMENT_VERIFIED', 'Payment verified'), ('PAYMENT_REJECTED', 'Payment rejected'), ('CERTIFICATE_AUTHORIZED', 'Certificate authorized')], max_length=40, verbose_name='notification type'),
        ),
    ]

