# Generated by Django 4.2.30 on 2026-08-05 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_authorized_certificates(apps, schema_editor):
    FormSubmission = apps.get_model('forms_builder', 'FormSubmission')
    CertificateRecord = apps.get_model('forms_builder', 'CertificateRecord')
    for submission in FormSubmission.objects.filter(certificate_authorized=True).select_related(
        'event_form__event'
    ):
        event_year = submission.event_form.event.starts_at.year
        short_token = str(submission.participant_token).replace('-', '')[:10].upper()
        CertificateRecord.objects.create(
            submission_id=submission.pk,
            certificate_number=f'CERT-{event_year}-{short_token}',
            status='AUTHORIZED',
            authorized_by_id=submission.certificate_authorized_by_id,
            authorized_at=(submission.certificate_authorized_at or submission.updated_at),
            created_by_id=submission.certificate_authorized_by_id,
            updated_by_id=submission.certificate_authorized_by_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms_builder', '0020_formsubmission_certificate_authorized_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CertificateRecord',
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_reference', ''), _negated=True), fields=('method', 'transaction_reference'), name='unique_nonempty_payment_reference_per_method'),
        ),
        migrations.CreateModel(
            name='CertificateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('certificate_number', models.CharField(max_length=50, unique=True, verbose_name='certificate number')),
                ('status', models.CharField(choices=[('AUTHORIZED', 'Authorized'), ('REVOKED', 'Revoked')], db_index=True, default='AUTHORIZED', max_length=20, verbose_name='certificate status')),
                ('authorized_at', models.DateTimeField(verbose_name='authorized at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
                ('revocation_reason', models.TextField(blank=True, verbose_name='revocation reason')),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authorized_certificate_records', to=settings.AUTH_USER_MODEL, verbose_name='authorized by')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_certificate_records', to=settings.AUTH_USER_MODEL, verbose_name='revoked by')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_record', to='forms_builder.formsubmission', verbose_name='participant submission')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'certificate',
                'verbose_name_plural': 'certificates',
                'ordering': ['-authorized_at'],
            },
        ),
        migrations.RunPython(
            migrate_authorized_certificates,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='certificate_authorized',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='certificate_authorized_at',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='certificate_authorized_by',
        ),
    ]

