# Generated by Django 4.2.30 on 2026-08-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0021_delete_certificaterecord_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='certificaterecord',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('revoked_at__isnull', True), ('revoked_by__isnull', True), ('status', 'AUTHORIZED')), models.Q(('revoked_at__isnull', False), ('revoked_by__isnull', False), ('status', 'REVOKED')), _connector='OR'), name='valid_certificate_lifecycle_state'),
        ),
        migrations.AddConstraint(
            model_name='formanswer',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('text_value', ''), _negated=True), ('number_value__isnull', False), _negated=True), name='answer_scalar_exclusive_01'),
        ),
        migrations.AddConstraint(
            model_name='formanswer',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('text_value', ''), _negated=True), ('date_value__isnull', False), _negated=True), name='answer_scalar_exclusive_02'),
        ),
        migrations.AddConstraint(
            model_name='formanswer',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('text_value', ''), _negated=True), ('datetime_value__isnull', False), _negated=True), name='answer_scalar_exclusive_03'),
        ),
        migrations.AddConstraint(
            model_name='formanswer',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('text_value', ''), _negated=True), ('boolean_value__isnull', False), _negated=True), name='answer_scalar_exclusive_04'),
        ),
        migrations.AddConstraint(
            model_name='formanswer',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('text_value', ''), _negated=True), ('uploaded_file__isnull', False), models.Q(('uploaded_file', ''), _negated=True), _negated=True), name='answer_scalar_exclusive_05'),
        ),
        migrations.AddConstraint(
            model_name='formanswer',
            constraint=models.CheckConstraint(check=models.Q(('number_value__isnull', False), ('date_value__isnull', False), _negated=True), name='answer_scalar_exclusive_06'),
        ),
        migrations.AddConstraint(
            model_name='formanswer',
            constraint=models.CheckConstraint(check=models.Q(('number_value__isnull', False), ('datetime_value__isnull', False), _negated=True), name='answer_scalar_exclusive_07'),
        ),
        migrations.AddConstraint(
            model_name='formanswer',
            constraint=models.CheckConstraint(check=models.Q(('number_value__isnull', False), ('boolean_value__isnull', False), _negated=True), name='answer_scalar_exclusive_08'),
        ),
        migrations.AddConstraint(
            model_name='formanswer',
            constraint=models.CheckConstraint(check=models.Q(('number_value__isnull', False), ('uploaded_file__isnull', False), models.Q(('uploaded_file', ''), _negated=True), _negated=True), name='answer_scalar_exclusive_09'),
        ),
        migrations.AddConstraint(
            model_name='formanswer',
            constraint=models.CheckConstraint(check=models.Q(('date_value__isnull', False), ('datetime_value__isnull', False), _negated=True), name='answer_scalar_exclusive_10'),
        ),
        migrations.AddConstraint(
            model_name='formanswer',
            constraint=models.CheckConstraint(check=models.Q(('date_value__isnull', False), ('boolean_value__isnull', False), _negated=True), name='answer_scalar_exclusive_11'),
        ),
        migrations.AddConstraint(
            model_name='formanswer',
            constraint=models.CheckConstraint(check=models.Q(('date_value__isnull', False), ('uploaded_file__isnull', False), models.Q(('uploaded_file', ''), _negated=True), _negated=True), name='answer_scalar_exclusive_12'),
        ),
        migrations.AddConstraint(
            model_name='formanswer',
            constraint=models.CheckConstraint(check=models.Q(('datetime_value__isnull', False), ('boolean_value__isnull', False), _negated=True), name='answer_scalar_exclusive_13'),
        ),
        migrations.AddConstraint(
            model_name='formanswer',
            constraint=models.CheckConstraint(check=models.Q(('datetime_value__isnull', False), ('uploaded_file__isnull', False), models.Q(('uploaded_file', ''), _negated=True), _negated=True), name='answer_scalar_exclusive_14'),
        ),
        migrations.AddConstraint(
            model_name='formanswer',
            constraint=models.CheckConstraint(check=models.Q(('boolean_value__isnull', False), ('uploaded_file__isnull', False), models.Q(('uploaded_file', ''), _negated=True), _negated=True), name='answer_scalar_exclusive_15'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='payment_amount_not_negative'),
        ),
    ]

