# Generated by Django 4.2.30 on 2026-08-06 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms_builder', '0022_certificaterecord_valid_certificate_lifecycle_state_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='certificaterecord',
            name='valid_certificate_lifecycle_state',
        ),
        migrations.AddField(
            model_name='certificaterecord',
            name='denial_reason',
            field=models.TextField(blank=True, verbose_name='denial reason'),
        ),
        migrations.AddField(
            model_name='certificaterecord',
            name='denied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='denied at'),
        ),
        migrations.AddField(
            model_name='certificaterecord',
            name='denied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='denied_certificate_records', to=settings.AUTH_USER_MODEL, verbose_name='denied by'),
        ),
        migrations.AlterField(
            model_name='certificaterecord',
            name='authorized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='authorized at'),
        ),
        migrations.AlterField(
            model_name='certificaterecord',
            name='status',
            field=models.CharField(choices=[('AUTHORIZED', 'Authorized'), ('DENIED', 'Not authorized'), ('REVOKED', 'Revoked')], db_index=True, default='AUTHORIZED', max_length=20, verbose_name='certificate status'),
        ),
        migrations.AddConstraint(
            model_name='certificaterecord',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('denied_at__isnull', True), ('denied_by__isnull', True), ('revoked_at__isnull', True), ('revoked_by__isnull', True), ('status', 'AUTHORIZED')), models.Q(('authorized_at__isnull', True), ('authorized_by__isnull', True), ('denied_at__isnull', False), ('denied_by__isnull', False), ('revoked_at__isnull', True), ('revoked_by__isnull', True), ('status', 'DENIED')), models.Q(('authorized_at__isnull', False), ('authorized_by__isnull', False), ('denied_at__isnull', True), ('denied_by__isnull', True), ('revoked_at__isnull', False), ('revoked_by__isnull', False), ('status', 'REVOKED')), _connector='OR'), name='valid_certificate_lifecycle_state'),
        ),
    ]

