# Generated by Django 4.2.30 on 2026-08-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0023_remove_certificaterecord_valid_certificate_lifecycle_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('REGISTRATION_RECEIVED', 'Registration received'), ('REGISTRATION_APPROVED', 'Registration approved'), ('REGISTRATION_REJECTED', 'Registration rejected'), ('CHECK_IN_CONFIRMED', 'Check-in confirmed'), ('EVENT_REMINDER', 'Event reminder'), ('PAYMENT_RECEIVED', 'Payment received'), ('PAYMENT_VERIFIED', 'Payment verified'), ('PAYMENT_REJECTED', 'Payment rejected'), ('CERTIFICATE_AUTHORIZED', 'Certificate authorized'), ('CERTIFICATE_DENIED', 'Certificate not authorized')], max_length=40, verbose_name='notification type'),
        ),
    ]

