# Generated by Django 4.2.29 on 2026-08-27 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms_builder', '0027_normalize_incomplete_submission_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayLogicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('match_type', models.CharField(choices=[('ALL', 'Match all rules (AND)'), ('ANY', 'Match any rule (OR)')], default='ALL', max_length=3)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('event_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_logic_groups', to='forms_builder.eventform')),
                ('target_question', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='display_logic', to='forms_builder.formquestion')),
                ('target_section', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='display_logic', to='forms_builder.formsection')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'display logic group',
                'verbose_name_plural': 'display logic groups',
            },
        ),
        migrations.CreateModel(
            name='DisplayLogicRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('operator', models.CharField(choices=[('EQUALS', 'equals'), ('NOT_EQUALS', 'does not equal'), ('CONTAINS', 'contains'), ('NOT_CONTAINS', 'does not contain'), ('ANY_OF', 'is any of'), ('NONE_OF', 'is none of'), ('ANSWERED', 'is answered'), ('NOT_ANSWERED', 'is not answered'), ('GREATER_THAN', 'is greater than'), ('LESS_THAN', 'is less than'), ('DATE_BEFORE', 'is before date'), ('DATE_AFTER', 'is after date')], max_length=30)),
                ('comparison_value', models.TextField(blank=True)),
                ('comparison_values', models.JSONField(blank=True, default=list)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='forms_builder.displaylogicgroup')),
                ('source_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='display_logic_rules', to='forms_builder.formquestion')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'display logic rule',
                'verbose_name_plural': 'display logic rules',
                'ordering': ['display_order', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='displaylogicgroup',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('target_question__isnull', True), ('target_section__isnull', False)), models.Q(('target_question__isnull', False), ('target_section__isnull', True)), _connector='OR'), name='logic_group_has_exactly_one_target'),
        ),
    ]
