# Generated by Django 4.2.29 on 2026-08-28 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0028_displaylogicgroup_displaylogicrule_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='displaylogicgroup',
            name='logic_group_has_exactly_one_target',
        ),
        migrations.AddField(
            model_name='displaylogicgroup',
            name='parent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_groups', to='forms_builder.displaylogicgroup'),
        ),
        migrations.AddField(
            model_name='displaylogicrule',
            name='comparison_question',
            field=models.ForeignKey(blank=True, help_text="Compare with this question's answer instead of a fixed value.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='display_logic_comparison_rules', to='forms_builder.formquestion'),
        ),
        migrations.AddField(
            model_name='displaylogicrule',
            name='comparison_value_end',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='displaylogicrule',
            name='operator',
            field=models.CharField(choices=[('EQUALS', 'equals'), ('NOT_EQUALS', 'does not equal'), ('CONTAINS', 'contains'), ('NOT_CONTAINS', 'does not contain'), ('ANY_OF', 'is any of'), ('NONE_OF', 'is none of'), ('ANSWERED', 'is answered'), ('NOT_ANSWERED', 'is not answered'), ('GREATER_THAN', 'is greater than'), ('GREATER_THAN_OR_EQUAL', 'is greater than or equal to'), ('LESS_THAN', 'is less than'), ('LESS_THAN_OR_EQUAL', 'is less than or equal to'), ('BETWEEN', 'is between'), ('STARTS_WITH', 'starts with'), ('ENDS_WITH', 'ends with'), ('SELECTION_COUNT_EQUALS', 'has exactly this many selections'), ('SELECTION_COUNT_AT_LEAST', 'has at least this many selections'), ('SELECTION_COUNT_AT_MOST', 'has at most this many selections'), ('DATE_BEFORE', 'is before date'), ('DATE_AFTER', 'is after date')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='displaylogicgroup',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('parent_group__isnull', True), ('target_question__isnull', True), ('target_section__isnull', False)), models.Q(('parent_group__isnull', True), ('target_question__isnull', False), ('target_section__isnull', True)), models.Q(('parent_group__isnull', False), ('target_question__isnull', True), ('target_section__isnull', True)), _connector='OR'), name='logic_group_is_root_target_or_nested'),
        ),
    ]
