# Generated by Django 4.2.29 on 2026-08-29 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0031_choice_filters'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='displaylogicgroup',
            name='logic_group_is_root_target_or_nested',
        ),
        migrations.AddField(
            model_name='displaylogicgroup',
            name='target_required_question',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_logic', to='forms_builder.formquestion'),
        ),
        migrations.AddConstraint(
            model_name='displaylogicgroup',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('parent_group__isnull', True), ('target_question__isnull', True), ('target_required_question__isnull', True), ('target_section__isnull', False)), models.Q(('parent_group__isnull', True), ('target_question__isnull', False), ('target_required_question__isnull', True), ('target_section__isnull', True)), models.Q(('parent_group__isnull', True), ('target_question__isnull', True), ('target_required_question__isnull', False), ('target_section__isnull', True)), models.Q(('parent_group__isnull', False), ('target_question__isnull', True), ('target_required_question__isnull', True), ('target_section__isnull', True)), _connector='OR'), name='logic_group_is_root_target_or_nested'),
        ),
    ]
