# Generated by Django 4.2.29 on 2026-08-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0032_conditional_required_logic'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='formanswer',
            name='unique_answer_per_submission_question',
        ),
        migrations.AddField(
            model_name='eventform',
            name='advanced_expression_mode',
            field=models.BooleanField(default=False, help_text='For expert builders only. Enables safe raw calculation and validation expressions; arbitrary Python or JavaScript is never executed.', verbose_name='enable advanced expression mode'),
        ),
        migrations.AddField(
            model_name='formanswer',
            name='repeat_index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='repeat entry number'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='is_repeatable',
            field=models.BooleanField(default=False, help_text='Allow respondents to add multiple entries for this section.', verbose_name='repeatable section'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='maximum_repeats',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='maximum entries'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='minimum_repeats',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='minimum entries'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='repeat_label_en',
            field=models.CharField(blank=True, max_length=80, verbose_name='entry label in English'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='repeat_label_sw',
            field=models.CharField(blank=True, max_length=80, verbose_name='entry label in Kiswahili'),
        ),
        migrations.AddConstraint(
            model_name='formanswer',
            constraint=models.UniqueConstraint(fields=('submission', 'question', 'repeat_index'), name='unique_answer_per_submission_question'),
        ),
    ]
