# Generated by Django 4.2.29 on 2026-06-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SummitParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('institution', models.CharField(max_length=200)),
                ('designation', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('attendance_type', models.CharField(choices=[('Physical', 'Physical'), ('Online', 'Online')], default='Physical', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
