# Generated by Django 4.2.29 on 2026-06-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0002_summitparticipant_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='summitparticipant',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summitparticipant',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summitparticipant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='summit/photos/'),
        ),
        migrations.AddField(
            model_name='summitparticipant',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='summit/qrcodes/'),
        ),
    ]
