# Generated by Django 4.2.29 on 2026-06-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0003_summitparticipant_checked_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summitparticipant',
            name='other_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='summitparticipant',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('Mx.', 'Mx.'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
