# Generated by Django 4.2.29 on 2026-06-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0004_summitparticipant_other_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summitparticipant',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('Mx.', 'Mx.'), ('Hon.', 'Hon.'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
