# Generated by Django 4.2.29 on 2026-06-25 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0005_alter_summitparticipant_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('venue', models.CharField(default='Not specified', max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),

        migrations.AlterField(
            model_name='summitparticipant',
            name='designation',
            field=models.CharField(default='Not specified', max_length=150),
        ),
        migrations.AlterField(
            model_name='summitparticipant',
            name='email',
            field=models.EmailField(default='notprovided@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='summitparticipant',
            name='full_name',
            field=models.CharField(default='Not specified', max_length=150),
        ),
        migrations.AlterField(
            model_name='summitparticipant',
            name='institution',
            field=models.CharField(default='Not specified', max_length=200),
        ),
        migrations.AlterField(
            model_name='summitparticipant',
            name='phone',
            field=models.CharField(default='Not specified', max_length=30),
        ),
        migrations.AlterField(
            model_name='summitparticipant',
            name='region',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='summitparticipant',
            name='title',
            field=models.CharField(
                choices=[
                    ('Mr.', 'Mr.'),
                    ('Ms.', 'Ms.'),
                    ('Dr.', 'Dr.'),
                    ('Prof.', 'Prof.'),
                    ('Mx.', 'Mx.'),
                    ('Hon.', 'Hon.'),
                    ('Other', 'Other'),
                ],
                default='Mr.',
                max_length=20
            ),
        ),

        migrations.AddField(
            model_name='summitparticipant',
            name='event',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='participants',
                to='summit.summitevent'
            ),
        ),

        migrations.AddConstraint(
            model_name='summitparticipant',
            constraint=models.UniqueConstraint(
                fields=('event', 'full_name', 'email', 'phone'),
                name='unique_participant_per_event_name_email_phone'
            ),
        ),
    ]