# Generated by Django 4.2.29 on 2026-06-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0006_summitevent_alter_summitparticipant_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summitevent',
            name='registration_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='summit/event_qrcodes/'),
        ),
    ]
