# Generated by Django 4.2.29 on 2026-06-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0007_summitevent_registration_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='summitevent',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summitevent',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
