# Generated by Django 4.2.29 on 2026-06-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0008_summitevent_is_archived_summitevent_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='summitevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summitevent',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
