# Generated by Django 4.2.29 on 2026-06-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0009_summitevent_end_time_summitevent_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='summitevent',
            name='badge_footer_text',
            field=models.CharField(default='Ministry of Education, Science and Technology', max_length=200),
        ),
        migrations.AddField(
            model_name='summitevent',
            name='badge_use_watermark',
            field=models.BooleanField(default=True),
        ),
    ]
