# Generated by Django 4.2.29 on 2026-07-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='browser',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='http_method',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
