# Generated by Django 4.2.29 on 2026-03-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskassignment_last_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='management_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='management_note_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
