# Generated by Django 4.2.29 on 2026-03-20 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_task_management_note_task_management_note_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='management_note_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_management_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='management_note_role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
