# Generated by Django 4.2.29 on 2026-03-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_returned_at_task_returned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='carried_forward_progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
