# Generated by Django 4.2.29 on 2026-03-25 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_taskassignment_carried_forward_progress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskassignment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='taskupdate',
            options={},
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('RETURNED', 'Returned')], default='ASSIGNED', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskupdate',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
