# Generated by Django 4.2.29 on 2026-07-10 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0010_userprofile_approval_role'),
        ('tasks', '0007_alter_taskassignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='permits.department'),
        ),
        migrations.AddField(
            model_name='task',
            name='department_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='permits.departmentunit'),
        ),
    ]
