# Generated by Django 4.2.30 on 2026-07-26 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms_builder', '0004_participant_badge_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('checked_in_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='checked in at')),
                ('method', models.CharField(choices=[('QR', 'QR code'), ('MANUAL', 'Manual lookup')], default='QR', max_length=20, verbose_name='check-in method')),
                ('notes', models.TextField(blank=True, verbose_name='check-in notes')),
                ('checked_in_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participant_check_ins', to=settings.AUTH_USER_MODEL, verbose_name='checked in by')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_in', to='forms_builder.formsubmission', verbose_name='participant submission')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'participant check-in',
                'verbose_name_plural': 'participant check-ins',
                'ordering': ['-checked_in_at'],
            },
        ),
    ]

