# Generated by Django 4.2.29 on 2026-07-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='allow_task_assignment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='allow_task_completion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='allow_task_creation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='allow_task_export',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='allow_task_progress_update',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='open_task_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
