# Generated by Django 4.2.29 on 2026-07-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_admin', '0002_systemsetting_allow_task_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='allow_badge_print',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='allow_group_permit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='allow_individual_permit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='allow_permit_cancel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='allow_permit_edit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='allow_permit_export',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='allow_permit_print',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='allow_qr_code',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='open_permit_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
